cmd/db_test.go, dev/docker-compose-sdp-anchor.yml, helmchart/sdp/values.yaml, internal/data/assets_test.go, internal/data/fixtures.go, internal/db/migrations/2023-08-15.0-alter-issuer-constraints.sql, internal/serve/httphandler/assets_handler.go, internal/serve/httphandler/assets_handler_test.go, internal/serve/httphandler/stellar_toml_handler.go, internal/serve/httphandler/stellar_toml_handler_test.go, internal/services/send_payments_service.go, internal/services/send_payments_service_test.go, internal/services/setup_assets_for_network_service.go, internal/services/setup_assets_for_network_service_test.go, internal/transactionsubmission/transaction_worker_test.go
Add support to disburse the Stellar Network native token - XLM. Also, add it to the asset default list.
The SDP should be able to disburse XLM.
N/A
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e9 …
=> [SDP-821] misc: add XLM asset support

stellar-auth/pkg/auth/jwt_manager.go, stellar-auth/pkg/auth/jwt_manager_test.go, stellar-auth/pkg/auth/manager.go
Increase the authentication token refresh period from 30s to 2min.
We are facing too many logouts due to the low refresh window we have for the authentication token. 
N/A …
=> [SDP-828] stellar-auth: increase the refresh authentication token period

cmd/channel_accounts.go, cmd/channel_accounts_test.go, cmd/transaction_submitter.go, cmd/transaction_submitter_test.go, helmchart/sdp/values.yaml
Increase base fee
During tests with the demo instance, we noticed some payments failing or taking too long to succeed.
A higher (default) fee will be more resilient. …
=> [Chore] Increase base fee

internal/htmltemplate/tmpl/receiver_otp_message.tmpl, internal/serve/httphandler/receiver_send_otp_handler.go
Update the OTP message to start with the OTP code.
Also, add the org name in the SMS message.
UX improvement.
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/commo …
=> SDP-862 update the OTP message to start with the OTP code

cmd/channel_accounts.go, cmd/channel_accounts_test.go, internal/transactionsubmission/README.md, internal/transactionsubmission/horizon.go, internal/transactionsubmission/horizon_test.go, internal/transactionsubmission/services/channel_account_service.go, internal/transactionsubmission/services/channel_accounts_service_test.go
SDP-795 Remove TSS configs that could allow unencrypted ChannelAccount private keys to be saved in the database
Security improvement to prevent someone from misconfigure this in production. …
=> SDP-795 Remove TSS configs that could allow unencrypted ChannelAccount private keys to be saved in the database

internal/serve/httphandler/login_handler.go, internal/serve/httphandler/login_handler_test.go, internal/serve/httphandler/mfa_handler.go, internal/serve/httphandler/mfa_handler_test.go, internal/serve/httphandler/profile_handler.go, internal/serve/httphandler/profile_handler_test.go, internal/serve/httphandler/reset_password_handler.go, internal/serve/httphandler/reset_password_handler_test.go, internal/serve/httphandler/user_handler.go, internal/serve/httphandler/user_handler_test.go, stellar-auth/pkg/auth/auth.go, stellar-auth/pkg/auth/auth_test.go, stellar-auth/pkg/auth/mocks.go
Adding the following logs 
* Account Lifecycle Logging: Must log creation and deletion of user accounts.
* Password Management Logging: Must log all changes to user passwords.
* User Access Pattern Logging: Must log new login instances of user logins.
To have a comprehensive application security log system that includes tracking of account lifecycle events, password management actions, and user access patterns, with timestamps and user associations in order to effectively monitor, detect, and respond to unauthorized access or malicious activities within the system, ensuring transparency, accountability, and compliance with security standards.
[TODO or N/A]
[`pr-preview`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e988411 …
=> SDP-800 add application activity Logs

internal/serve/httphandler/login_handler.go, internal/serve/httphandler/login_handler_test.go
Change error code from 500 to 401 as suggested by Marcelo https://stellarorg.sentry.io/issues/4442947505/activity/?alert_rule_id=14391750&alert_type=issue&project=4505189092556800&referrer=slack
The specific error in the above sentry log was triggered when the frontend that does not have reCAPTCHA enabled attempts to access the login, but we want to return a more suitable status code for the response
[TODO or N/A]
[`dev`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/backend-helm- …
=> [SDP-867] Change status code for when reCAPTCHA token cannot be validated

internal/anchorplatform/object_schemas.go, internal/anchorplatform/platform_api_service.go, internal/anchorplatform/platform_api_service_mock.go, internal/anchorplatform/platform_api_service_test.go, internal/serve/httphandler/verifiy_receiver_registration_handler.go, internal/serve/httphandler/verifiy_receiver_registration_handler_test.go
Update PATCH {AP}/transaction body with the appropriate fields.
We had a task to review if we were PATCHING the correct fields, and it turns out we were sending no-op fields that were being ignored by the AP. …
=> SDP-465: Update PATCH {AP}/transaction body with the appropriate fields

internal/transactionsubmission/transaction_worker.go, internal/transactionsubmission/transaction_worker_test.go, internal/transactionsubmission/utils/errors.go, internal/transactionsubmission/utils/errors_test.go
- Moved horizon tx error parsing logic to utils file
- Call crash tracker when tx should be marked as an error
[TODO or N/A] …
=> [SDP-774] Update tx worker to use crash tracker on failed tx's

internal/anchorplatform/platform_api_service.go, internal/data/fixtures.go, internal/data/payments.go, internal/data/receivers_wallet.go, internal/data/receivers_wallet_test.go, internal/db/migrations/2023-07-17.2-add-status-history-column-submitter-transactions-table.sql, internal/db/migrations/2023-09-17.0-add-anchor-platform-tx-id.sql, internal/serve/httphandler/verifiy_receiver_registration_handler.go, internal/serve/httphandler/verifiy_receiver_registration_handler_test.go, internal/transactionsubmission/utils/utils_test.go
Store the Anchor Platform's tx ID when registering a receiver's wallet
So we can PATCH the AP with the success/error states later.
I'm storing the AP ID in the receiver wallet entry, because this is the DB row that gets updated when we complete the SEP24 registration.
We don't know exactly the amount that will be updated there, but we can update the amount when we PATCH the success/failure responses.
Alternatively, we could store the AnchorPlatform ID in a payment row, but since that is not used in the registration flow, it seemed inconsistent to rely on that table for this part of the flow while the registration does not rely on payments.
[`pr-preview`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/ …
=> SDP-488: store the Anchor Platform's tx ID when registering a receiver's wallet

internal/serve/httphandler/user_handler.go, internal/serve/httphandler/user_handler_test.go
Prevent users from deactivating themselves
If you deactivate your own user, you'll get locked out and the product may end up without any user having access to it. …
=> SDP-892: prevent users from deactivating themselves

internal/serve/httphandler/assets_handler.go, internal/serve/httphandler/assets_handler_test.go
Add an option to specify a custom `GetPreconditionsFn` parameter in the AssetsHandler object.
To address the intermittent test failure ([example](https://github.com/stellar/stellar-disbursement-platform-backend/actions/runs/6200706140/job/16835930483?pr=40)) where the test assertion would fail because the time.Now() call generated in the test would differ from the one generated in the code by a second. …
=> SDP-884: solve intermittent test failure due to timestamp comparison

internal/data/receiver_verification.go, internal/data/receiver_verification_test.go, internal/serve/httphandler/verifiy_receiver_registration_handler_test.go
This PR increases the maximum attempts for the receiver validate its PII.
Avoid blocking the receiver forever from receiving the payment.
N/A
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e9884117 …
=> [SDP-898] data: increase max attempts to the receiver validate the PII

internal/serve/httphandler/verifiy_receiver_registration_handler.go, internal/serve/httphandler/verifiy_receiver_registration_handler_test.go
Rather than just specifying a generic error message in the response, we want to show some message to the users about exceeding the verification limit.
[TODO or N/A]
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/demo/demo-back …
=> [SDP-565] Inform user if they have exceeded the maximum attempts at verification

internal/data/organizations.go, internal/serve/httphandler/profile_handler.go, internal/serve/httphandler/profile_handler_test.go
This PR adds the attributes `sms_registration_message_template` and `otp_message_template` to the response body of `GET /organizations` endpoint. These attributes will only be returned when they aren't the default values.
These messages will be displayed by the client on the settings screen.
N/A
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/ste …
=> [SDP-905] data/httphandler: serve SMS templates

internal/data/payments.go, internal/data/payments_test.go
Use `COALESCE` for nullable fields to avoid conversion errors.
The fields aren't a pointer so we need to coalesce the value to an empty string instead.
N/A …
=> data: use COALESCE for nullable fields

internal/data/organizations.go, internal/data/organizations_test.go, internal/db/migrations/2023-10-12.0.alter-organizations-table-add-sms-resend-interval.sql, internal/serve/httphandler/profile_handler.go, internal/serve/httphandler/profile_handler_test.go
This PR adds a new column on the `organizations` table - `sms_resend_interval`. Also, adds this field in the `PATCH /organizations` endpoint.
This new column will control the interval of resending the Invitation SMS to the receivers when they don't get registered after receiving the first invitation. The value of this column can be `null` or an integer greater than `0 (zero)`. `Null` means that the organization doesn't want to automatically resend the invitation SMS. To set this field as null a request with the number 0 (zero) should be sent.
- This new column will be used in the next [PR](https://github.com/stellar/stellar-disbursement-platform-backend/pull/66). 
- Create a pull request in the stellar-docs adding this new attribute. …
=> [SDP-815] data/httphandler: add sms_resend_interval to organizations table

internal/serve/httphandler/verifiy_receiver_registration_handler.go, internal/serve/httphandler/verifiy_receiver_registration_handler_test.go, internal/serve/publicfiles/js/receiver_registration.js
Return better error messages during receiver registration. 
Help the receiver troubleshoot registration issues. 
[TODO or N/A]
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev …
=> SDP-915 Improve error messages during receiver registration process

internal/serve/httphandler/profile_handler.go, internal/serve/httphandler/profile_handler_test.go
Add `sms_resend_interval` attribute on the response of endpoint `GET /organization`.
Show the `sms_resend_interval` on the UI.
[TODO or N/A]
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171 …
=> chore: add sms resend interval attr on the get organization info endpoint

internal/data/fixtures.go, internal/data/wallets.go, internal/data/wallets_test.go, internal/serve/httphandler/disbursement_handler.go, internal/serve/httphandler/disbursement_handler_test.go, internal/serve/httphandler/wallets_handler.go, internal/serve/httphandler/wallets_handler_test.go, internal/services/disbursement_management_service.go, internal/services/disbursement_management_service_test.go
* Add `enabled` flag for `GET /wallets` to return only enabled wallets. 
* Change `POST /disbursements` to fail when using a disabled wallet.
* Change **StartDisbursement** to fail when using a disabled wallet. 
This feature complements the `Wallet Providers Configuration` feature. 
[TODO or N/A]
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/st …
=> SDP-930 add wallets filtering by enabled flag

stellar-multitenant/pkg/cli/add_tenants.go, stellar-multitenant/pkg/cli/add_tenants_test.go, stellar-multitenant/pkg/cli/root.go, stellar-multitenant/pkg/tenant/manager.go, stellar-multitenant/pkg/tenant/manager_test.go, stellar-multitenant/pkg/tenant/tenant.go
This PR adds a new CLI command in the `stellar-multitenant` package. This CLI is responsible for registering new `tenants` on the main database schema. The `tenant name` is unique.
```sh
mtn add-tenants myorg
``` 
We should be able to register new `tenants`.
This process only registers the new `tenant` in the main database schema but we are missing creating the database schema and configuring the basics for it.
[`dev`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/backend-helm-val …
=> [SDP-913] stellar-multitenant: add-tenants cmd

stellar-multitenant/internal/db/migrations/2023-10-16.0.add-tenants-table.sql, stellar-multitenant/pkg/cli/config_tenant.go, stellar-multitenant/pkg/cli/root.go, stellar-multitenant/pkg/cli/utils/custom_set_value.go, stellar-multitenant/pkg/tenant/manager.go, stellar-multitenant/pkg/tenant/manager_test.go, stellar-multitenant/pkg/tenant/tenant.go, stellar-multitenant/pkg/tenant/tenant_test.go
This PR adds the `config-tenant` CLI command in the `stellar-multitenant` package. This command sets the basic environment variables for the tenants individually. Each flag of the command is optional, but at least one should be provided when running it. When a flag is not provided the corresponding value in the database will not be changed. To change a value it should be explicitly passed when running the CLI. 
The `tenant-id` is required to run the CLI.
```sh
mtn config-tenant --tenant-id abc --enable-mfa "false" --distribution-public-key "GBDYRFO3ZJ74UQ6V36D2PHXRXBYW52HKUYRYCWSFIGWQSPJMN4ARBGIF"
```
We should be able to configure the tenants' environment variables.
We are still not able to set up `secrets`.
Missing tests for the CLI. …
=> [SDP-913] stellar-multitenant: add config-tenant command

internal/services/patch_anchor_platform_transactions_completion.go, internal/services/patch_anchor_platform_transactions_completion_test.go
Truncate error messages before patching transactions on the anchor platform.
We were sending an error message with more than 255 characters which causes an error on the Anchor Platform.
Closes #70 
N/A …
=> [SDP-933] services: truncate error messages before patching to anchor platform

internal/data/disbursements.go, internal/data/disbursements_test.go, internal/data/receivers.go, internal/data/receivers_test.go, internal/data/receivers_wallet.go, internal/data/receivers_wallet_test.go, internal/serve/httphandler/receiver_handler_test.go
Get canceled payments for disbursement and receiver metrics
statistics metrics on FE
N/A
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/externalse …
=> [httphandler/data] get canceled payment status for disbursement and receivers metrics

db/migrations/tenant-migrations/2023-10-16.0.add-tenants-table.sql, internal/services/disbursement_management_service.go, internal/utils/network_type.go, stellar-multitenant/pkg/cli/add_tenants.go, stellar-multitenant/pkg/cli/add_tenants_test.go, stellar-multitenant/pkg/cli/utils/custom_set_value.go, stellar-multitenant/pkg/tenant/fixtures.go, stellar-multitenant/pkg/tenant/manager.go, stellar-multitenant/pkg/tenant/manager_test.go, stellar-multitenant/pkg/tenant/tenant.go, stellar-multitenant/pkg/tenant/tenant_test.go
This PR adds a new method to the `Multitenant Manager` called `ProvisionNewTenant` which adds a new tenant to the `tenants` table, creates a new database schema for this new tenant, runs the database migrations on this new schema, and finally register a user on the `auth_users` table on that schema.
The `add-tenants` CLI command was changed to use this new method.
We should be able to provision a new tenant without caring about the transport layer that was used (API call, CLI, etc...).
We should send the invitation email to the user registered in the database. We're going to do this in another PR.
[`pr-preview`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/stellar-disburse …
=> [SDP-759] stellar-multitenant: provision new tenant

internal/serve/httphandler/user_handler.go, internal/serve/httphandler/user_handler_test.go, internal/services/create_auth_user.go, internal/services/create_auth_user_test.go, internal/services/disbursement_management_service.go, stellar-multitenant/pkg/cli/add_tenants.go, stellar-multitenant/pkg/cli/add_tenants_test.go, stellar-multitenant/pkg/cli/utils/custom_set_value.go, stellar-multitenant/pkg/tenant/manager.go, stellar-multitenant/pkg/tenant/manager_test.go
This PR creates a new service that creates a new user and sends the invitation email. We refactor to use this service when creating a new user on the user HTTP handler and provisioning a new tenant.
We should send an invitation email when provisioning a new tenant.
N/A
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/ …
=> [SDP-952] stellar-multitenant/services: send invitation email

db/db.go, db/db_connection_pool_with_metrics.go, db/db_connection_pool_with_metrics_test.go, db/db_connection_pool_with_router.go, db/db_connection_pool_with_router_test.go, db/db_test.go, db/migrate.go, db/migrations/sdp-migrations/2023-10-25.0-update-payments-status-type-and-organizations-table.sql, db/sql_exec_with_metrics_test.go, db/sql_exec_with_router.go, db/sql_exec_with_router_test.go, internal/data/assets_test.go, internal/data/countries_test.go, internal/data/wallets_test.go, internal/serve/httphandler/assets_handler_test.go, internal/serve/httphandler/payments_handler.go, internal/serve/serve.go, internal/serve/serve_test.go, stellar-auth/pkg/auth/auth.go, stellar-multitenant/pkg/cli/add_tenants.go, stellar-multitenant/pkg/cli/add_tenants_test.go, stellar-multitenant/pkg/router/multitenant_data_source_router.go, stellar-multitenant/pkg/router/multitenant_data_source_router_test.go, stellar-multitenant/pkg/tenant/manager.go, stellar-multitenant/pkg/tenant/manager_test.go
* Additions are separated from refactors and done in this commit 7eb0cc54182886f535946501c2292cc4748d0dbb
* Changes to `db` package
* add `DataSourceRouter` interface that will be used for routing users to the correct datasource using the context
* add `SQLExecutorWithRouter` a SQLExecutor that leverages the router to direct users to the correct connection pool
* add `ConnectionPoolWithRouter` a ConnectionPool that uses routing. 
* Changes to `stellar-multitenant` 
* add `MultiTenantDataSourceRouter` an implementation of `DataSourceRouter` that uses tenant information to perform routing to the correct datasource. 
* Added `ctx` to interfaces and implementations in the `db` package to prepare the ground for multi-tenancy. These changes are done in separate commits to help with reviews 👀
* …
=> SDP-761 - Multitenant Connection Pool & DataSource Router

cmd/db.go, cmd/db_test.go, db/migrate.go, db/migrate_test.go, dev/docker-compose-sdp-anchor.yml, helmchart/sdp/templates/02.1-deployment-sdp.yaml, internal/integrationtests/docker-compose-e2e-tests.yml, stellar-multitenant/pkg/cli/add_tenants_test.go, stellar-multitenant/pkg/cli/migrate.go, stellar-multitenant/pkg/cli/migrate_test.go, stellar-multitenant/pkg/tenant/fixtures.go, stellar-multitenant/pkg/tenant/manager.go, stellar-multitenant/pkg/tenant/manager_test.go, v1_compatibility/docker-compose.yml
This PR modifies the SDP's `db` CLI command and `setup-for-network` CLI command to be tenant-aware. It means being able to run these commands for all or a specific tenant.
We should be able to apply the migrations to the tenants and also setup it for the given network.
Fix the e2e test and SDP anchor platform compatibility.
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171 …
=> [SDP-953] cmd: change the migrate CLI to be tenant aware

cmd/db_test.go, internal/services/setup_wallets_for_network_service_test.go
Make setup-wallets-for-network tests more flexible. 
This would make adding new wallets simpler. 
[TODO or N/A]
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/com …
=> SDP-972 make setup-wallets-for-network tests more flexible

.github/CODEOWNERS, .github/workflows/anchor_platform_integration_check.yml, .github/workflows/e2e_integration_test.yml
* Add CODEOWNERS to protect main and develop branches
* Change `secrets` to `vars` to facilitate running github actions for PRs coming from forked repositories.
=> chore: add CODEOWNERS and change secrets to vars.

internal/serve/validators/disbursement_instructions_validator.go, internal/serve/validators/disbursement_instructions_validator_test.go
Add verification for DOB verification info to check if the date is in the future.
Properly validate DOB verification. 
[TODO or N/A]
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube0 …
=> SDP-688 - Verification DOB validation missing when date is in the future

cmd/db_test.go, internal/services/assets/assets_pubnet.go, internal/services/assets/assets_testnet.go, internal/services/setup_assets_for_network_service.go, internal/services/setup_assets_for_network_service_test.go, internal/services/wallets/wallets_pubnet.go, internal/services/wallets/wallets_testnet.go
Refactoring `setup_assets_for_network_service` to simplify wallet setup. 
Currently wallets have to input assets manually when adding an entry. We want to simplify that. 
[TODO or N/A] …
=> chore: Refactor assets to simplify Wallet Setup

db/migrations/tenant-migrations/2023-10-16.0.add-tenants-table.sql, stellar-multitenant/pkg/cli/config_tenant.go, stellar-multitenant/pkg/internal/httphandler/tenants_handler.go, stellar-multitenant/pkg/internal/httphandler/tenants_handler_test.go, stellar-multitenant/pkg/internal/validators/tenant_validator.go, stellar-multitenant/pkg/internal/validators/tenant_validator_test.go, stellar-multitenant/pkg/tenant/fixtures.go, stellar-multitenant/pkg/tenant/manager.go, stellar-multitenant/pkg/tenant/manager_test.go, stellar-multitenant/pkg/tenant/tenant.go, stellar-multitenant/pkg/tenant/tenant_test.go
- Remove **Distribution account** from tenant configuration
- Remove **SEP 10 account** from tenant configuration
- **SEP 10 account**: We will only need one SEP10 account for the whole SDP instance (all tenants). SEP10 is used for authentication between the wallet and the SDP (host). Anchor wouldn't work with one SEP10 account per organization.
- **Distribution account**: Distribution account will be set at the organization level. Regardless of how we will decide to provision and configure the distribution account, it won't be a configuration at the tenant level. We don't want to the admins (hosts) to know anything about the orgs distribution account. 
[TODO or N/A]
[`pr-preview`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a9 …
=> SDP-969 - Remove Distribution account and SEP10 account from tenant config

cmd/serve.go, cmd/serve_test.go, dev/docker-compose-sdp-anchor.yml, internal/serve/httphandler/stellar_toml_handler.go, internal/serve/httphandler/stellar_toml_handler_test.go, internal/serve/serve.go, stellar-auth/pkg/auth/jwt_manager.go, stellar-multitenant/pkg/router/multitenant_data_source_router.go, stellar-multitenant/pkg/router/multitenant_data_source_router_test.go, stellar-multitenant/pkg/tenant/fixtures.go, stellar-multitenant/pkg/tenant/manager.go
- Currently we can't start up Anchor platform because it attempts fetching a TOML file without specifying a tenant. 
- We need a way to identify the instance's TOML file. 
- Fix anchor tests
TOML file currently gets generated based on one organization’s name, assets and distribution accounts. 
We need to change the  SDP TOML file to be dynamically generated depending on knowledge of the tenant. We will have a distinction between a tenant’s TOML file and the host’s TOML file. 
- Has the aggregated list of assets supported by all tenants
- Anchor needs this on startup. 
- Has the information of a particular tenant. 
- Used during wallet registration process.
=> SDP-977 Generate a Multi-tenant SEP1 TOML

internal/data/disbursements.go, internal/serve/httphandler/receiver_handler.go, internal/serve/httphandler/receiver_handler_test.go, internal/serve/serve.go, internal/serve/serve_test.go, internal/services/wallets/wallets_pubnet.go
API endpoint to get the verification types
GET `receiver/verification-types` 
Add dropdown for choosing Verification Type when creating new disbursements on FE
N/A …
=> [SDP-960] serve/httphandler: API endpoint to fetch the verification types

.github/workflows/e2e_integration_test.yml, cmd/serve.go, cmd/serve_test.go, dev/docker-compose-frontend.yml, dev/docker-compose-sdp-anchor.yml, dev/docker-compose-tss.yml, dev/docker-compose.yml, dev/main.sh, internal/serve/serve.go, internal/serve/serve_test.go
- Add new environment variable `ENABLE_SCHEDULER`  (default: false): This flag enables the scheduler. Scheduler will remain disabled until work on Kafka is completed. 
- Add new environment variable `ENABLE_MULTITENANT_DB` (default: true): When this flag is enabled, we use the Multi-tenant connection pool with router for the API. When it's disabled, we use the single tenant connection pool. 
- Set `CORS_ALLOWED_ORIGINS: "*"` in docker-compose. This is needed until we fix SDP-980
- Use `multitenant-alpha` frontend-image for docker-compose. 
- Disable TSS for docker-compose. This will remain disabled until work on Kafka is completed. 
- `main.sh` add scripts for creating example tenants during local development. 
- Disable `e2e tests` when PR target is `sdp-multitenant`. This will remain …
=> SDP-977 - Multi-tenant Docker Compose

dev/docker-compose-frontend.yml, dev/docker-compose-sdp-anchor.yml, dev/docker-compose-tss.yml, dev/docker-compose.yml
Refactor docker-compose to move 'depends_on' settings to top-level docker-compose.yml
Extended services may not use depends_on.
https://docs.docker.com/compose/compose-file/05-services/#restrictions
N/A
* [ x] This PR has reasonably narrow scope (if not, break it down into smaller PRs).
* [ x This PR does not mix refactoring changes with feature changes (split into two PRs otherwise).
* [x ] This PR's title starts with the name of the package, area, or subject affected by the change.
* [ x] This PR adds tests for the new functionality or fixes.
* [ x] This PR contains the link to the Jira ticket it addresses.
* [ x] No new CONFIG variables are required -OR- the new required ones were added to the helmchart's [`values.yaml`] file.
* [ x] No new CONFIG variables are required -OR- the new …
=> docker-compose.yml refactor 

internal/data/wallets.go
Add missing space when building the query
The previous code was creating the string `%sGROUP BY...` instead of `%s GROUP BY`.
I wonder why the unit tests were succeeding in the PRs but failing in local host. …
=> [SDP-1008] Add missing space when building the query

.github/pull_request_template.md, internal/data/assets.go, internal/data/assets_test.go, internal/serve/httphandler/assets_handler.go, internal/serve/httphandler/assets_handler_test.go, internal/services/send_receiver_wallets_invite_service.go, internal/services/send_receiver_wallets_invite_service_test.go
Make `POST /assets` idempotent.
The previous implementation was causing a hassle with a partner that had seeded their database before using the frontend application. …
=> [SDP-996] Make `POST /assets` idempotent

CHANGELOG.md, cmd/db_test.go, helmchart/sdp/Chart.yaml, internal/services/setup_wallets_for_network_service_test.go, internal/services/wallets/wallets_pubnet.go, main.go
Update client_domain on Vibrant Assist from api.vibrantapp.com to vibrantapp.com.
It was incorrect.
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews …
=> [SDP-1022] Hotfix: update Vibrant Assist's `client_domain`

internal/data/models.go, internal/data/receiver_verification.go, internal/data/receiver_verification_test.go, internal/htmltemplate/tmpl/receiver_register.tmpl, internal/serve/httphandler/receiver_registration.go, internal/serve/httphandler/receiver_send_otp_handler.go, internal/serve/httphandler/receiver_send_otp_handler_test.go, internal/serve/publicfiles/js/receiver_registration.js, internal/serve/serve.go, internal/serve/validators/receiver_registration_validator.go, internal/serve/validators/receiver_registration_validator_test.go
Modify the `SEP-24` flow to perform verification for an entered phone number based on the latest verification type.
The current `SEP-24` flow is hardcoded to only accept date of birth but we will have disbursement files that will include pin and national id, and the front-end will need to change to be able to parse those values.
example of the flow using `PIN`
The same tests have been repeated with `DATE_OF_BIRTH` and `NATIONAL_ID`
[TODO or N/A]
[`dev`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-dis …
=> [SDP-962] Change SEP-24 Flow to display different verifications based on Disbursement's verification type

db/migrate_test.go, db/migrations/tenant-migrations/2023-11-14.0.drop-unused-cors-column.sql, stellar-multitenant/pkg/cli/config_tenant.go, stellar-multitenant/pkg/cli/utils/custom_set_value.go, stellar-multitenant/pkg/internal/httphandler/tenants_handler.go, stellar-multitenant/pkg/internal/httphandler/tenants_handler_test.go, stellar-multitenant/pkg/internal/validators/tenant_validator.go, stellar-multitenant/pkg/internal/validators/tenant_validator_test.go, stellar-multitenant/pkg/tenant/fixtures.go, stellar-multitenant/pkg/tenant/manager.go, stellar-multitenant/pkg/tenant/manager_test.go, stellar-multitenant/pkg/tenant/tenant.go, stellar-multitenant/pkg/tenant/tenant_test.go
Matching kube PR https://github.com/stellar/kube/pull/1859
Experimented with multiple solutions to enable CORS in multi-tenancy. We don't need to have a CORS configuration per tenant as we originally thought, we can use a generic wildcard config thanks to this library https://github.com/rs/cors. 
We originally thought that we will need to define one cors configuration per tenant as CORS headers either allow wildcard `*` or a strict domain e.g. `https://redcorp.mtn-sdp-backend-dev.stellar.org` , `https://bluecorp.mtn-sdp-backend-dev.stellar.org` 
The initial implementation I tested relied on that concept 
```go
func CorsMiddleware(corsAllowedOrigins []string) func(http.Handler) http.Handler {
return func(next http.Handler) http.Handler {
return http.HandlerFunc(func(w http.ResponseWriter, …
```
=> SDP-980 Remove CORS from tenant configuration

internal/data/payments_state_machine.go, internal/data/payments_state_machine_test.go, internal/serve/httphandler/payments_handler.go, internal/serve/httphandler/payments_handler_test.go, internal/serve/serve.go, internal/serve/serve_test.go, internal/services/payment_management_service.go, internal/services/payment_management_service_test.go
Implement a new endpoint PATCH /payments/{id}/status that allows the user to change the status of an individual payment
UNHCR asked for the ability to cancel individual payments. 
Make sure to return an error if the transition is not possible. We only allow payments in ready status to be cancelled. There is a state machine that can be used to check if the transition is possible.
[`demo`]: …
=> [SDP-1025]: New endpoint to cancel individual payment in ready status

cmd/utils/custom_set_value.go, cmd/utils/custom_set_value_test.go
This PR fixes the `SetConfigOptionURLList` adding a check if the config value is empty.
It was returning errors even if it wasn't a required value.
N/A
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937 …
=> cmd: verify if the URL List config value is required

internal/serve/httphandler/receiver_send_otp_handler.go
Add a disclaimer to the SMS message warning users about the risk of sharing their wallet registration OTP with a third party.
This should address the open issue [SDP-012](https://docs.google.com/spreadsheets/d/1SiDnx3sRHNa4PBPZwrPKwwlUKPhUl-1vTWNHR7rFA4Q/edit#gid=0) in Coinspect's most recent report.
[TODO or N/A]
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001 …
=> [SDP-1031] Coinspect SDP-012 Enhance User Awareness for SMS One-Time Password (OTP) Usage

internal/serve/httphandler/user_handler.go, internal/serve/httphandler/user_handler_test.go, stellar-auth/pkg/cli/add_user.go
Log the user activity when updating users' info (updating roles, creating users through CLI).
Security review.
N/A
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/ …
=> [SDP-1030] cmd/httphandler: log user activity when updating users' info

cmd/serve.go, cmd/serve_test.go, dev/docker-compose-sdp-anchor.yml, helmchart/sdp/values.yaml, internal/serve/httphandler/forgot_password_handler.go, internal/serve/httphandler/forgot_password_handler_test.go, internal/serve/httphandler/login_handler.go, internal/serve/httphandler/login_handler_test.go, internal/serve/serve.go
SDP is currently using the instance’s environment variables ENABLE_MFA and ENABLE_RECAPTCHA to control security for auth functionality.  We want to instead use Tenant.EnableMFA and Tenant.EnableReCaptcha.
To have these controls be tenant-specific. 
N/A
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/demo/demo-backend …
=> [SDP-984] cmd/httphandler: Use tenant's configuration for `EnableMFA` and `EnableReCaptcha`

cmd/channel_accounts.go, cmd/channel_accounts_test.go, cmd/db/db.go, cmd/db/tss_migrations.go, cmd/db/tss_migrations_test.go, cmd/db_test.go, cmd/transaction_submitter.go, db/dbtest/dbtest.go, db/dbtest/dbtest_test.go, db/migrations/sdp-migrations/2023-07-05.0-tss-transactions-table-constraints.sql, db/migrations/sdp-migrations/2024-01-03.0-drop-submitter-transactions-table.sql, db/migrations/sdp-migrations/2024-01-03.1-drop-channel-accounts-table.sql, db/router/router.go, db/router/router_test.go, internal/transactionsubmission/engine/signature_service_test.go, internal/transactionsubmission/horizon.go, internal/transactionsubmission/horizon_test.go, internal/transactionsubmission/manager_test.go, internal/transactionsubmission/services/channel_accounts_service_test.go, internal/transactionsubmission/store/channel_account_test.go, internal/transactionsubmission/store/channel_transaction_bundle_test.go, internal/transactionsubmission/store/fixtures_test.go, internal/transactionsubmission/store/transactions_test.go, internal/transactionsubmission/transaction_worker_test.go, stellar-multitenant/pkg/cli/add_tenants_test.go, stellar-multitenant/pkg/internal/httphandler/tenants_handler_test.go, stellar-multitenant/pkg/internal/provisioning/manager_test.go, stellar-multitenant/pkg/router/multitenant_data_source_router_test.go, stellar-multitenant/pkg/tenant/manager.go, stellar-multitenant/pkg/tenant/manager_test.go
Move all TSS-related tables to the tss schema.
Close https://stellarorg.atlassian.net/browse/SDP-1001.
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previ …
=> [SDP-1001] Move all TSS-related tables to the tss schema

.github/workflows/ci.yml, db/migrations/tss-migrations/2024-01-05.0-add-tenant-id-to-submitter-transactions-table.sql, internal/services/payment_from_submitter_service_test.go, internal/services/payment_to_submitter_service.go, internal/services/payment_to_submitter_service_test.go, internal/transactionsubmission/manager_test.go, internal/transactionsubmission/store/channel_transaction_bundle_test.go, internal/transactionsubmission/store/fixtures.go, internal/transactionsubmission/store/fixtures_test.go, internal/transactionsubmission/store/transactions.go, internal/transactionsubmission/store/transactions_test.go, internal/transactionsubmission/transaction_worker.go, internal/transactionsubmission/transaction_worker_test.go
Add the `tenant_id` column to the TSS `submitter_transactions` table.
So we can associate every stellar_transaction to one tenant, using this to execute per-tenant transactions using each Tenant's separate balance.
Closes https://stellarorg.atlassian.net/browse/SDP-1006.
The `payment_from_submitter_job` and `payment_to_submitter_job` tests were temporarily disabled. Thwy will start working again on SDP-924 and SDP-925.
[`dev`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/backend- …
=> [SDP-1006] Add the `tenant_id` column to the TSS `submitter_transactions` table

internal/data/organizations.go, internal/serve/httphandler/profile_handler.go, internal/serve/httphandler/profile_handler_test.go
Start logging important changes on user or organization profiles, for traceability. Here are the functions that are now being logged:
- Changes made through `PatchOrganizationProfile`
- Log message: `log.Ctx(ctx).Warnf("[PatchOrganizationProfile] - userID %s will update the organization fields %v", user.ID, nonEmptyKeys)`
- Changes made through `PatchUserProfile`
- Log message: `log.Ctx(ctx).Warnf("[PatchUserProfile] - Will update email for userID %s to %s", user.ID, utils.TruncateString(reqBody.Email, 3))`
- Changes made through `PatchUserPassword`
- Log message: `log.Ctx(ctx).Warnf("[UpdateUserPassword] - Will update password for user account ID %s", user.ID)`
Also, refactored some tests.
So we can better track changes made in user profiles or Organization profiles, for accountability. …
=> [SDP-1032] Add logs for any changes in user profile or the organization profile

stellar-auth/pkg/auth/authenticator.go, stellar-auth/pkg/auth/authenticator_test.go, stellar-auth/pkg/auth/password_encrypter.go, stellar-auth/pkg/auth/password_encrypter_test.go, stellar-auth/pkg/cli/add_user.go, stellar-auth/pkg/cli/add_user_test.go
Follow up to #143. Mainly just adjusting any reference to the min password length from 8 to 12.
[TODO or N/A] …
=> [Fix] make password length generation + encryption be consistent with validation reqs

.github/workflows/anchor_platform_integration_check.yml, dev/docker-compose-sdp-anchor.yml
This configuration was used to test wallet registration multi-tenancy. 
* `SEP10_HOME_DOMAINS: "redcorp.stellar.local:8000,bluecorp.stellar.local:8000"` defines the two tenants in the allowable home domains. 
* `SEP10_HOME_DOMAIN: ""` is needed as a workaround to bypass anchor's default values. 
* `SEP10_WEB_AUTH_DOMAIN: "localhost:8080"` defines the proper web auth domain. 
Tested that using the multi-tenant SDP as a home domain instead of the anchor works properly. The multi-tenant home domain is properly passed in the JWT token could be used to identify the tenant and register the wallet appropriately. 
* The example tenants used in `SEP10_HOME_DOMAINS` are actually coming from the `dev/main.sh` startup script that creates two tenants `redcorp` and `bluecorp`. 
[TODO or N/A] …
=> SDP-927 - [SEP24] add configuration for multi-tenant registration flow

helmchart/sdp/templates/03.1-service-sdp.yaml
We need to expose the admin port 8003 in order to be able to access the admin from outside of the container. 
This doesn't create an Ingress to the admin API.
=> chore - expose admin port for the service

stellar-multitenant/pkg/internal/httphandler/tenants_handler.go, stellar-multitenant/pkg/internal/httphandler/tenants_handler_test.go
When tenant name is already in use we should return 400 instead of 500 http error. 
An incorrect HTTP status code is returned when creating a tenant with a name that already exists in the system.  The endpoint POST /tenants is currently returning a 500 Internal Server Error instead of the expected 400 Bad Request when a tenant creation request is made with a duplicate name.
[TODO or N/A]
[`demo`]: …
=> SDP-1063 Incorrect HTTP Status Code on Tenant Creation with Duplicate Name

internal/htmltemplate/tmpl/receiver_register.tmpl, internal/serve/httphandler/receiver_registration_test.go
Modify the receiver registration template to preload the google recaptcha script in the header instead of doing so in the body.
@torisamples brought up this [issue](https://stellarfoundation.slack.com/archives/C04C9MLM9UZ/p1702420198999679) of the recaptcha taking too long to load or not loading at all at times. Preloading the script may help with the slowness.
[TODO or N/A]
[`demo`]: …
=> [SDP-1014] Preload reCAPTCHA script in attempt to mitigate component loading issues upon login

.github/workflows/ci.yml, internal/data/fixtures.go, internal/serve/httphandler/payments_handler_test.go, internal/serve/httphandler/user_handler.go, internal/serve/validators/payment_query_validator.go, internal/serve/validators/payment_query_validator_test.go, internal/transactionsubmission/manager_test.go
Add `exhaustive` check to the CI, and fix the missing enum cases surfaced by this check.
Go doesn't;t enforce enums to be exhaustive, so adding such a check guarantees that we're covering all the enum use cases properly.
[`pr-preview …
=> Chore: Update CI `check` to run the exhaustive validator

cmd/serve.go
After the merge of PR #159 an error instantiating `KafkaConsumer` occurred since a new change on PR #162 was introduced changing how to pass the config parameters on it.
It's breaking the code build.
N/A …
=> fix: kafka config error

internal/serve/serve.go
Remove the close connection statement.
The connection is being used by the `TenantManager` so we can't close it.
N/A
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespace …
=> fix: closed database connection

internal/data/payments.go, internal/data/payments_state_machine.go, internal/data/payments_test.go, internal/data/query_params.go, internal/serve/httphandler/disbursement_handler.go, internal/serve/httphandler/disbursement_handler_test.go, internal/serve/serve.go, internal/services/disbursement_management_service.go, internal/services/disbursement_management_service_test.go
Add a extra validation step before transitioning disbursement to the `READY` status to check whether distribution account holds enough of target asset balance to fulfill any pending payments along with the payments on the target disbursement.
Pending payments from other disbursements are any in the status
- `PAUSED`
- `READY`
- `PENDING`
and exclude those in any terminal statuses `SUCCESS`, `CANCELED` and `FAILED` as we as `PAUSED` as those payments can remain in that state indefinitely.
[TODO or N/A]
[`pr-preview`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/stellar-disbursement-pl …
=> [SDP-1049] Validate the Distribution account balance before starting a Disbursement

CHANGELOG.md, internal/db/migrations/2023-07-05.0-tss-transactions-table-constraints.sql, internal/db/migrations/2024-02-05.0-tss-transactions-table-amount-constraing.sql, internal/transactionsubmission/store/transactions_test.go
Fix TSS's database amount precision to be compliant with the Stellar network amount precision.
The database amount was configured to NUMERIC(10,7), which allows the maximum value of 999.9999999. This is not compliant with the Stellar network amounts though, which according with the [docs](https://developers.stellar.org/docs/fundamentals-and-concepts/stellar-data-structures/assets#amount-precision) supports numbers from 0.0000001 to 922,337,203,685.4775807.
[`dev`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/ …
=> [Hot-fix] TSS amount precision

internal/transactionsubmission/utils/utils_test.go
Attempt to fix intermittent error in `transactionsubmission/utils/utils_test.go:47`
There are intermittent errors happening when acquiring the advisory lock, like https://github.com/stellar/stellar-disbursement-platform-backend/actions/runs/7790057714/job/21243057987?pr=172 for instance:
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-dis …
=> Chore: attempt to fix intermittent error in `transactionsubmission/utils/utils_test.go:47`

internal/data/assets.go, internal/data/assets_test.go, internal/serve/httphandler/disbursement_handler.go, internal/services/disbursement_management_service.go, internal/services/disbursement_management_service_test.go
Fix Distribution account balance validation that fails when the intended asset is XLM.
Also, improve the error message when the validation fails to the following format:
XLM:
USDC: …
=> [SDP-1088] Fix distribution account balance validation that fails when the intended asset is XLM

internal/data/disbursement_instructions.go, internal/data/disbursement_instructions_test.go
Clear error message about which receiver (line in CSV & phone number / internal id) that has a mis-matching verification. 
If the user doesn't know which record is causing the error, they won't know where to check to find the original value.
N/A
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/demo/demo-backend-helm-v …
=> SDP-575: [data] Improve receiver verification error messaging for disbursement instructions

dev/docker-compose-frontend.yml, dev/docker-compose-sdp-anchor.yml, dev/docker-compose-tss.yml, dev/docker-compose.yml
* Enable TSS in docker-compose for SDP multi-tenant
* Rename containers for SDP multi-tenant so that developers can run both mtn and single tenant versions side-by-side. 
* Fix `SEP10_HOME_DOMAINS` for anchor configuration 
https://stellarorg.atlassian.net/browse/SDP-1073
[TODO or N/A]
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbu …
=> [SDP-1073] Enable TSS for multi-tenant SDP

.github/workflows/docker_image_public_release.yml
Not run e2e when releasing sdp-multitenant docker image. 
This will be re-enabled as part of https://stellarorg.atlassian.net/browse/SDP-968
Docker image release for sdp-multitenant is marked as failed. 
[TODO or N/A]
[`pr-preview …
=> chore: stop running e2e on mtn docker push

.github/workflows/ci.yml, go.list, go.mod, go.sum, helmchart/sdp/values.yaml, internal/serve/serve.go, internal/serve/serve_test.go
Implement in-memory rate-limiting in the server, sensitive to the pair {IP, endpoint}. It's configured to a max of 10 requests every 20 seconds, which translates to a maximum of 30 requests per minute per IP, segregated per endpoint.
Also, add rate-limit to the k8s Ingress manifest.
For increased security against bots.
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/ku …
=> [SDP-1089] Add rate-limiters both in the application and the k8s deployment

internal/data/receiver_verification.go, internal/data/receiver_verification_test.go, internal/serve/httphandler/update_receiver_handler.go, internal/serve/httphandler/update_receiver_handler_test.go
Now we upsert the receivers' verification info.
*Note:* Only *NOT* confirmed verification info will be updated.
The caller will be able to update/insert these entries.
N/A …
=> [SDP-1106] data/httphandler: upsert receivers' verification info

internal/serve/httphandler/disbursement_handler.go, internal/serve/httphandler/disbursement_handler_test.go, internal/serve/validators/disbursement_instructions_validator.go, internal/serve/validators/disbursement_instructions_validator_test.go
* Trim spaces for all fields in disbursement instructions
Resolve https://stellarorg.atlassian.net/browse/SDP-1118
Phone number with extra spaces especially, may result in creation of duplicate receivers. 
[TODO or N/A]
[`pr-preview …
=> [SDP-1118] Hotfix: sanitize disbursement instructions

internal/data/receiver_verification.go, internal/data/receiver_verification_test.go
The order should be by `updated_at` and then by `verification_field` in alphabetical order.
SDP-1106
N/A
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-pre …
=> fix: ensure verification field order

.github/workflows/ci.yml, internal/serve/serve.go, internal/serve/serve_test.go
Adding authentication to `GET /organization/logo` 
Logos need to be able to resolve the tenant name. Making the endpoint authenticated solves this issue as we can reliably resolve the tenant id from the jwt token. 
FE PR: https://github.com/stellar/stellar-disbursement-platform-frontend/pull/79
Jira: https://stellarorg.atlassian.net/browse/SDP-1095
n/a
[`demo`]: …
=> [SDP-1095] Add Authentication to GET `/organization/logo` 

cmd/channel_accounts.go, cmd/db/db.go, cmd/serve.go, cmd/transaction_submitter.go, internal/dependencyinjection/container.go, internal/dependencyinjection/container_test.go, internal/dependencyinjection/fixtures.go, stellar-multitenant/pkg/cli/add_tenants.go, stellar-multitenant/pkg/cli/config_tenant.go
Rename dependency injection methods:
- `DeleteAndCloseInstanceByKey` -> `CleanupInstanceByKey`
- `DeleteAndCloseInstanceByValue` -> `DeleteAndCloseInstanceByValue`
As suggested in PR #207. …
=> [Chore] Rename methods, as suggested in PR #207

cmd/auth.go, cmd/channel_accounts.go, cmd/integration_tests.go, cmd/message.go, cmd/root.go, cmd/transaction_submitter.go, internal/crashtracker/sentry_client.go, internal/data/payments.go, internal/scheduler/scheduler.go, internal/serve/httphandler/disbursement_handler.go, internal/serve/httphandler/reset_password_handler.go, internal/serve/httphandler/stellar_toml_handler.go, internal/serve/httphandler/wallets_handler.go, internal/serve/middleware/middleware.go, internal/serve/middleware/middleware_test.go, internal/serve/serve.go, internal/serve/validators/disbursement_instructions_validator.go, internal/serve/validators/receiver_registration_validator.go, internal/serve/validators/wallet_validator.go, internal/serve/validators/wallet_validator_test.go, internal/services/ready_payments_cancellation_service.go, stellar-auth/cmd/stellarauth/main.go, stellar-auth/pkg/cli/add_user.go, stellar-auth/pkg/cli/migrate.go, stellar-auth/pkg/cli/root.go, stellar-multitenant/cmd/stellarmultitenant/main.go, stellar-multitenant/pkg/cli/add_tenants.go, stellar-multitenant/pkg/cli/config_tenant.go, stellar-multitenant/pkg/cli/root.go, stellar-multitenant/pkg/internal/provisioning/manager.go
Update logs usage to include the request info and use the context in all log calls. Basically, the changes are:
- `log.Debug(...)` -> `log.Ctx(ctx).Debug(...)`
- `log.Info(...)` -> `log.Ctx(ctx).Info(...)`
- `log.Warn(...)` -> `log.Ctx(ctx).Warn(...)`
- `log.Error(...)` -> `log.Ctx(ctx).Error(...)`
- `log.Fatal(...)` -> `log.Ctx(ctx).Fatal(...)`
And also, updated the Logging middleware to inject the `method` and `path` into the context, so they show up whenever we call `log.Ctx(ctx)...`:
https://github.com/stellar/stellar-disbursement-platform-backend/blob/d7efea6923d6cc029f2955c93fc1cf80d554db13/internal/serve/middleware/middleware.go#L191-L192
Additionally, updated the AuthenticateMiddleware to inject the `user_id` into the context: …
=> [Chore] Update logs usage to include the request info and use the context in all log calls

internal/transactionsubmission/monitor/monitor_service.go, internal/transactionsubmission/monitor/monitor_service_test.go, internal/transactionsubmission/transaction_worker.go, internal/transactionsubmission/transaction_worker_test.go
* Renamed `MonitorPayment` to `LogAndMonitorTransaction` for improved clarity.
* Started using the updated paymentLog in LogAndMonitorTransaction earlier than before, for a more complete debugging
* Added more fields to `LogAndMonitorTransaction`
* Validate info previously raised in the TSS review call
Address https://stellarorg.atlassian.net/browse/SDP-1129.
[`demo`]: …
=> [SDP-1129] TSS tweaks from the TSS review call, and small improvements in the MonitorPayment method

cmd/serve.go, internal/scheduler/jobs/anchor_platform_auth_enforcement_job.go, internal/scheduler/jobs/job.go, internal/scheduler/jobs/mocks.go, internal/scheduler/jobs/ready_payments_cancellation_job.go, internal/scheduler/scheduler.go, internal/scheduler/scheduler_test.go, internal/services/ready_payments_cancelation_service_test.go, internal/services/ready_payments_cancellation_service.go
* Make `ready_payments_cancellation` job multi-tenant
* Introduce a framework for running schedule jobs in a multi-tenant fashion. 
* Jobs have a new method `IsMultiTenant()` that's used to determine is a job is multi-tenant or not. 
* When the worker is about to process a multi-tenant job, it fetches the list of tenants and runs the job once for every tenant. 
```
DEBU[2024-03-11T13:42:22.310-07:00] Enqueuing job: ready_payments_cancellation    pid=15992
DEBU[2024-03-11T13:42:22.330-07:00] Processing job ready_payments_cancellation for tenant aee4b490-953c-45d9-b7f4-20cecb71d1de on worker 3  pid=15992
DEBU[2024-03-11T13:42:22.350-07:00] automatic ready payment cancellation is deactivated for bluecorp. Set a valid value to the organization's payment_cancellation_period_days to activate …
```
=> [SDP-1059] Make `ready_payments_cancellation` job multi-tenant

internal/serve/middleware/middleware.go, internal/serve/middleware/middleware_test.go, internal/serve/serve.go
Multi-tenant instance breaks when the user is logged in using the base domain. 
`InjectTenantMiddleware` was trying to fetch tenant ID from the token, but `AuthenticateMiddleware` only added the token to the request context later.
N/A …
=> [SDP-1132] serve: Multi-tenant instance breaks when user is logged in using the base domain.

dev/README.md, dev/docker-compose-monitoring.yml, dev/docker-compose-sdp-anchor.yml, dev/docker-compose.yml
simplify the main docker-compose to reduce the number of containers started. 
Currently we’re starting 11 containers: 
- 1 init container
- 7 containers needed for running the SDP
- Kafka, sdp db, sdp frontend, sdp api, anchor db, anchor, tss. 
- 3 containers for monitoring kafka (conduktor)
We’re splitting the 3 containers for monitoring kafka into their own docker-compose that we’re calling docker-compose-monitoring. We can add containers like Grafana and Prometheus here for optionally starting a monitoring stack for the SDP.
https://stellarorg.atlassian.net/browse/SDP-1142
[`pr-preview`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/stellar-disbursement-platform/backend- …
=> [SDP-1142] simplify docker-compose by splitting monitoring containers

stellar-multitenant/pkg/internal/httphandler/tenants_handler.go, stellar-multitenant/pkg/internal/httphandler/tenants_handler_test.go, stellar-multitenant/pkg/internal/validators/tenant_validator.go
This PR removes the `distribution_account` field from the requests of `POST` and `PATCH` of the Admin API.
This field should not be changed externally.
N/A …
=> stellar-multitenant: remove distribution account from admin api handlers

cmd/serve.go, internal/events/events.go, internal/events/mocks.go, internal/scheduler/jobs/payment_from_submitter_job.go, internal/scheduler/jobs/payment_from_submitter_job_test.go, internal/services/mocks/payment_from_submitter_service.go, internal/services/payment_from_submitter_service.go, internal/services/payment_from_submitter_service_test.go, internal/services/payment_to_submitter_service.go, internal/transactionsubmission/store/mocks/transaction_store.go, internal/transactionsubmission/store/store.go, internal/transactionsubmission/store/transactions.go, internal/transactionsubmission/store/transactions_test.go
There are two issues fixed in this PR, both were not causing functional changes but were causing errors in the logs. 
1. Introduce a `NoopProducer` that logs events - in the case where `EVENT_BROKER_TYPE=NONE` 
2. Add `tenant-id` as a parameter to `payments_from_submitter` job. Given that this jobs goes from TSS -> SDP, we need to determine which tenant to use to fetch the txs from submitter_tx 
[TODO or N/A]
[`dev`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/backend-helm-value …
=> SDP-1141 - Using ENABLE_SCHEDULER throws an error when producing a message

cmd/serve.go, internal/events/eventhandlers/send_receiver_wallets_sms_invitation_event_handler.go, internal/scheduler/jobs/send_receiver_wallets_sms_invitation_job.go, internal/scheduler/jobs/send_receiver_wallets_sms_invitation_job_test.go, internal/services/send_receiver_wallets_invite_service.go, internal/services/send_receiver_wallets_invite_service_test.go
* change invitation links for receiver to contain the multi-tenant domain for the tenant. 
**Before:**
`You have a payment waiting for you from the bluecorp. 
Click https://demo-wallet.stellar.org?asset=USDC-GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5&domain=localhost&name=bluecorp&signature=ad1a6a70a80068d046e0e30937ed043a23dafea30e616cbc949a52586578a1a499933f5662f85fc636cc104cffd3281ce63022cbe4e84971207f3a521f11ae07 to register.`
**After:**
`Content: You have a payment waiting for you from the bluecorp. 
Click https://demo-wallet.stellar.org?asset=USDC-GBBD47IF6LWK7P7MDEVSCWR7DPUWV3NY3DTQEVFL4NAT4AQH3ZLLFLA5&domain=bluecorp.stellar.local&name=bluecorp&signature=fb1b5cdd446820d3aa02823c993d9fc1e05cd86a0764dc93bb9b37a8e701b4c8ff6eda368699ab5faeabdb07f012937e33210bfecc631e89457 …
=> [SDP-1119] fix the domain value used to produce the invitation link for MTN

helmchart/sdp/templates/01.3-configmap-tss.yaml
TSS configmap also had the wrong labels.
=> [SDP-1060] Fix TSS Configmap labels

internal/anchorplatform/object_schemas.go, internal/anchorplatform/object_schemas_test.go, internal/anchorplatform/platform_api_service.go, internal/anchorplatform/platform_api_service_test.go, internal/data/assets_test.go, internal/events/eventhandlers/patch_anchor_platform_transaction_completion_event_handler.go, internal/events/eventhandlers/patch_anchor_platform_transaction_completion_event_handler_test.go, internal/scheduler/jobs/patch_anchor_platform_transactions_job_test.go, internal/serve/httphandler/assets_handler.go, internal/services/patch_anchor_platform_transactions_completion.go, internal/services/patch_anchor_platform_transactions_completion_test.go, internal/utils/utils.go, internal/utils/utils_test.go
Fix bug when patching XLM with the Anchor Platform by making sure the native asset is represented as `stellar:native`.
To address the error https://stellarorg.sentry.io/issues/5043465348/events/9639627a676f4b4e8a0a0043d5b0b5ab/?project=4505189092556800.
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/demo/demo-backen …
=> [SDP-1149] Fix bug when patching XLM with the Anchor Platform

db/migrations/admin-migrations/2024-04-16-alter-tenants-table-drop-sms-email-type.sql, dev/main.sh, internal/integrationtests/admin_api.go, internal/integrationtests/integration_tests.go, stellar-multitenant/internal/httphandler/tenants_handler.go, stellar-multitenant/internal/httphandler/tenants_handler_test.go, stellar-multitenant/internal/validators/tenant_validator.go, stellar-multitenant/internal/validators/tenant_validator_test.go, stellar-multitenant/pkg/tenant/fixtures.go, stellar-multitenant/pkg/tenant/manager.go, stellar-multitenant/pkg/tenant/manager_test.go, stellar-multitenant/pkg/tenant/tenant.go, stellar-multitenant/pkg/tenant/tenant_test.go
- Remove `email_sender_type` and `sms_sender_type` from tenant configuration
- We decided not to wire those configurations. 
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/n …
=> [SDP-1156] Remove `email_sender_type` and `sms_sender_type` from tenant config

cmd/auth.go, cmd/root.go, cmd/serve.go, cmd/serve_test.go, cmd/utils/global_options.go, internal/utils/url.go, internal/utils/url_test.go, stellar-multitenant/internal/httphandler/tenants_handler.go, stellar-multitenant/internal/httphandler/tenants_handler_test.go, stellar-multitenant/internal/provisioning/manager.go, stellar-multitenant/internal/provisioning/manager_test.go, stellar-multitenant/internal/validators/tenant_validator.go, stellar-multitenant/internal/validators/tenant_validator_test.go, stellar-multitenant/pkg/serve/serve.go, stellar-multitenant/pkg/tenant/tenant.go
- Make `base_url` and `sdp_ui_base_url` optional fields in the `POST /tenants` request body. Skip validation on fields if left blank
- If left blank in the request, handler when dynamically generate the url's based on the name in the request and the base url attached to the server.
[TODO or N/A]
[`demo`]: …
=> [SDP-1148] Add `base_url` and `sdp_ui_base_url` default values

dev/migrate_1.1.6_to_2.0.0.sh
Fix 1.x to 2.x migration script.
The field name was updated from tenant.distribution_account to tenant.distribution_account_address.
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube0 …
=> Fix 1.x to 2.x migration script

dev/docker-compose-sdp-anchor.yml, dev/main.sh, internal/serve/httpclient/http_client.go, stellar-multitenant/internal/httphandler/tenants_handler.go, stellar-multitenant/internal/provisioning/manager.go, stellar-multitenant/pkg/serve/serve.go, stellar-multitenant/pkg/serve/serve_test.go
* Add some logging 
* Change timeout values to show some obfuscated errors. The problem was that different components were timing out at the same time which caused random errors to show up. 
```
--> Admin Server (35s) ---> HttpClient (30s) ----> Horizon (30s)*
```
```
--> Admin Server (50s) ---> HttpClient (40s) ----> Horizon (30s)*
```
[*] Horizon timeout is outside of our control
* SDP-1217 [Provisioning] Random failures when funding disbursement account
* SDP-1212 main.sh does not deal with response codes that are different from 2xx
[`dev`]: …
=> [SDP-1217] [SDP-1212] Provisioning script improvements

stellar-multitenant/internal/provisioning/manager.go, stellar-multitenant/internal/provisioning/manager_test.go
Make tenant provisioning atomic, even to failures in fundTenantDistributionAccount.
Address https://stellarorg.atlassian.net/browse/SDP-1208.
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e9884117 …
=> [SDP-1208] Make tenant provisioning atomic, even to failures in fundTenantDistributionAccount

internal/serve/httphandler/wallets_handler.go, internal/serve/middleware/middleware.go, internal/serve/middleware/middleware_test.go
Fix the `AnyRoleMiddleware` so it returns 403 (instead of 401) when the user role doesn't have the required role.
How it's being handled:
Addresses https://stellarorg.atlassian.net/browse/SDP-1215. …
=> [SDP-1215] Fix the `AnyRoleMiddleware` so it returns 403 (instead of 401) when the user role doesn't have the required role

internal/services/payment_to_submitter_service.go, internal/transactionsubmission/store/mocks/transaction_store.go
Make `sendPaymentsReadyToPay` atomic by synchronizing the database transactions
the atomicity was not done correctly.
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespac …
=> [SDP-1179] Make `sendPaymentsReadyToPay` atomic by synchronizing the database transactions

internal/services/disbursement_management_service.go, internal/services/disbursement_management_service_test.go
Include the distribution account address in the InsufficientBalanceError error message.
With different distribution accounts per tenants, this info makes debugging easier. …
=> [Chore] Include the distribution account address in the InsufficientBalanceError error message

internal/serve/httphandler/payments_handler.go, internal/serve/httphandler/payments_handler_test.go
Retry Payments were not working because of the absence of a `Key` when submitting a Kafka event. 
In the following test, I retried a failed payment a couple of times (receiver didn't have a trust line to USDC), then added the trust line and retried a 3rd time. Payment eventually succeeded. 
https://stellarorg.atlassian.net/browse/SDP-1213 
[TODO or N/A]
[`demo`]: …
=> [SDP-1213] Retry Payment Not Working

cmd/utils/custom_set_value.go, cmd/utils/shared_config_options.go
* Change `KAFKA_SECURITY_PROTOCOL` to be optional
* `KAFKA_SECURITY_PROTOCOL` is only required when `EVENT_BROKER_TYPE=kafka`.
* We can make it optional and let the validator take care of validating kafka configurations. 
When `EVENT_BROKER_TYPE=KAFKA` and `KAFKA_SECURITY_PROTOCOL` is not passed, we get the following error on startup : 
```
FATA[2024-05-31T17:08:24.769+01:00] error creating Kafka Producer: invalid kafka config: security protocol cannot be empty  pid=39478
```
[TODO or N/A]
[`dev`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e …
=> [SDP-1226] KAFKA_SECURITY_PROTOCOL config should be optional

dev/main.sh, internal/events/backoff_manager.go, internal/events/backoff_manager_test.go, internal/events/event_consumer.go, internal/events/event_consumer_test.go, internal/events/eventhandlers/patch_anchor_platform_transaction_completion_event_handler.go, internal/events/eventhandlers/payment_from_submitter_event_handler.go, internal/events/eventhandlers/payment_to_submitter_event_handler.go, internal/events/eventhandlers/send_receiver_wallets_sms_invitation_event_handler.go, internal/events/message.go, internal/events/message_test.go, internal/events/mocks.go
* When a message is consumed by Kafka, it is ran through the handler chain (list of handlers compatible with that message) 
* If a message fails on a consumer, it gets retried (re-runs through the handler chain) 
* When the message re-runs through the handler chain, it runs through all handlers (those on which it succeeded and those on which it failed) 
* Introduce a `SuccessfulExecutions` in the message to keep track of the history of successful executions 
* Introduce `ShouldHandleMessage` to determine the logic of when a message would be executed by a handler 
* Messages that already succeeded wouldn't be executed
**Logs after fix**
```
time="2024-05-31T11:05:03.174+01:00" level=info msg="starting consuming messages for topic test.test_topic..." pid=31444 …
```
=> [SDP-1219] Retry messages on failed handlers only

stellar-multitenant/internal/provisioning/manager.go
Chore: fix error handling when `distSignerType.DistributionAccountType()` returns an error.
Otherwise `handleProvisioningError()` will not deal with the error properly. …
=> Chore: fix error handling when `distSignerType.DistributionAccountType()` returns an error

internal/data/payments.go, internal/events/events.go, internal/events/events_test.go, internal/serve/httphandler/disbursement_handler_test.go, internal/serve/httphandler/payments_handler.go, internal/serve/httphandler/payments_handler_test.go, internal/serve/httphandler/receiver_wallets_handler.go, internal/serve/httphandler/receiver_wallets_handler_test.go, internal/serve/httphandler/verifiy_receiver_registration_handler.go, internal/serve/httphandler/verifiy_receiver_registration_handler_test.go, internal/serve/serve.go, internal/services/disbursement_management_service.go, internal/services/disbursement_management_service_test.go, internal/services/payment_from_submitter_service.go, internal/transactionsubmission/transaction_worker.go, internal/transactionsubmission/transaction_worker_test.go, stellar-auth/pkg/auth/mocks.go
Handle errors in message publishing in a consistent way:
- **Retry SMS invitation**: it now makes the change to the DB regardless of the event publishing succeeding. This way, the system is consistent and can rely on the scheduled jobs.
- **TSS->SDP**: when failing to publish an event, it's now triggering a crash report, so the sysadmin gets notified.
- **SEP-24 registration completed**, **New disbursement**, **Retry Payment**: all of these were returning a 500 and were changed to return a 2xx instead, and creating a crash report.
Additional changes:
- Removed `services.NewDisbursementManagementService` because it was going nothing except for increasing complexity
- Removed a redundant parameter from the DisbursementManagementService.
- Created `ProduceEvents` as a shared method to …
=> [SDP-1224] Improve how we handle erros on kafka event producers

internal/data/payments.go, internal/events/events.go, internal/events/events_test.go, internal/serve/httphandler/disbursement_handler_test.go, internal/serve/httphandler/payments_handler.go, internal/serve/httphandler/payments_handler_test.go, internal/serve/httphandler/receiver_wallets_handler.go, internal/serve/httphandler/receiver_wallets_handler_test.go, internal/serve/httphandler/verifiy_receiver_registration_handler.go, internal/serve/httphandler/verifiy_receiver_registration_handler_test.go, internal/serve/serve.go, internal/services/disbursement_management_service.go, internal/services/disbursement_management_service_test.go, internal/services/payment_from_submitter_service.go, internal/transactionsubmission/transaction_worker.go, internal/transactionsubmission/transaction_worker_test.go, stellar-auth/pkg/auth/mocks.go
Replay #304, by @marcelosalloum 
Handle errors in message publishing in a consistent way:
- **Retry SMS invitation**: it now makes the change to the DB regardless of the event publishing succeeding. This way, the system is consistent and can rely on the scheduled jobs.
- **TSS->SDP**: when failing to publish an event, it's now triggering a crash report, so the sysadmin gets notified.
- **SEP-24 registration completed**, **New disbursement**, **Retry Payment**: all of these were returning a 500 and were changed to return a 2xx instead, and creating a crash report.
Additional changes:
- Removed `services.NewDisbursementManagementService` because it was going nothing except for increasing complexity
- Removed a redundant parameter from the DisbursementManagementService.
- Created …
=> [SDP-1224] (Replay #304) Improve how we handle erros on kafka event producers

cmd/serve.go, cmd/serve_test.go, cmd/transaction_submitter.go, internal/events/events.go, internal/events/kafka.go, internal/events/mocks.go, internal/serve/httphandler/health_handler.go, internal/serve/httphandler/health_handler_test.go, internal/serve/serve.go, internal/serve/serve_test.go
* Adding Database and Kafka to healthcheck 
* Return 5xx when any of these two is failing. 
* Have a more accurate healthcheck 
* Not process requests when service is not fully operational to avoid inconsistent state. 
[TODO or N/A] …
=> [SDP-1229] Add database and Kafka to Healthcheck `GET /health` 

Dockerfile.development
This PR removes the argument from the Dockerfile.development entrypoint.  The reason is that helm provides the arg as the same docker container is used for both sdp and tss.
by hardcoding it, tss will fail, as it will startup as sdp instead of tss.
no known limitations.
* [x ] This PR has a reasonably narrow scope (if not, break it down into smaller PRs).
* [ x] This PR title and description are clear enough for anyone to review it.
* [x ] This PR does not mix refactoring changes with feature changes (split into two PRs otherwise).
* [x ] No new CONFIG variables are required -OR- the new required ones were added to the helmchart's [`values.yaml`] file.
* [ x] No new CONFIG variables are required -OR- the new required ones were added to the deployments ([`pr-preview`], [`dev`], [`demo`], …
=> remove "serve" from entrypoint.  its passed by helm

cmd/integration_tests.go, dev/main.sh, internal/integrationtests/admin_api.go, internal/integrationtests/integration_tests.go, stellar-multitenant/internal/httphandler/tenants_handler.go, stellar-multitenant/internal/httphandler/tenants_handler_test.go, stellar-multitenant/internal/validators/tenant_validator.go, stellar-multitenant/internal/validators/tenant_validator_test.go
Allow request `POST /tenants` to specify the signer type when provisioning a tenant's distribution account
[TODO or N/A] …
=> [SDP-1167] When provisioning a tenant, indicate the signer type

internal/serve/httphandler/balances_handler.go, internal/serve/httphandler/balances_handler_test.go
1. Provision a new tenant with distribution_account_type = DISTRIBUTION_ACCOUNT.CIRCLE.DB_VAULT 
e.g.
```
{
"name": "circle-alpha",
"owner_email": "marwen@stellar.org",
"owner_first_name": "Marwen",
"owner_last_name": "Owner",
"organization_name": "Circle Alpha Testing",
"sdp_ui_base_url": "https://circle-alpha.mtn-sdp-frontend-dev.stellar.org",
"base_url": "https://circle-alpha.mtn-sdp-backend-dev.stellar.org",
"distribution_account_type": "DISTRIBUTION_ACCOUNT.CIRCLE.DB_VAULT"
}
```
2. Call `GET /balances` endpoint before configuring Circle. 
1. Returns 400 error because circle account is not configured. 
1. Returns 500 error because of nil pointer 
[`pr-preview`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/ …
=> [SDP-1243] `GET /balances` return 500 when circle account is not activated

internal/serve/httphandler/balances_handler.go, internal/serve/httphandler/balances_handler_test.go, internal/serve/httphandler/circle_config_handler.go, internal/serve/httphandler/circle_config_handler_test.go, internal/serve/serve.go, internal/utils/mocks.go, stellar-multitenant/pkg/tenant/mocks.go
Update `PATCH /organization/circle-config` to:
1. Ping Circle to ensure the CIrcle API Key is correct
2. Get the Wallet from Circle, to ensure the walletID is correct.
3. Update the tenant's `DIstributionAccountStatus` to ACTIVE, once everything works out correctly.
To wrap up the tenant setup and to ensure the Circle data is correct.
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937 …
=> Update `PATCH /organization/circle-config` to ping Circle and to update the tenant data

internal/serve/httphandler/circle_config_handler.go, internal/serve/httphandler/circle_config_handler_test.go, internal/serve/httphandler/mfa_handler.go, internal/testutils/http.go
Add missing tenantID when updating the tenant from `PATCH /organization/circle-config`
It should have been added in #332 
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/name …
=> Fix: Add missing tenantID when updating the tenant from `PATCH /organization/circle-config`

cmd/serve.go, internal/circle/balance.go, internal/circle/balance_test.go, internal/circle/client_test.go, internal/circle/environments.go, internal/circle/service_test.go, internal/circle/transfer.go, internal/circle/transfer_test.go, internal/circle/wallet.go, internal/dependencyinjection/distribution_account_service.go, internal/dependencyinjection/distribution_account_service_test.go, internal/serve/httphandler/balances_handler.go, internal/serve/httphandler/balances_handler_test.go, internal/serve/httphandler/disbursement_handler_test.go, internal/services/disbursement_management_service.go, internal/services/disbursement_management_service_test.go, internal/services/distribution_account_service.go, internal/services/distribution_account_service_test.go, internal/services/mocks/distribution_account_service.go, stellar-multitenant/internal/httphandler/tenants_handler.go, stellar-multitenant/internal/httphandler/tenants_handler_test.go
During disbursement start, use Circle to fetch the available balance when the tenant uses Circle.
Address https://stellarorg.atlassian.net/browse/SDP-1232
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a …
=> [SDP-1232] During disbursement start, use Circle to fetch the available balance when the tenant uses Circle

stellar-multitenant/pkg/tenant/manager.go, stellar-multitenant/pkg/tenant/manager_test.go
When the Circle API actually responds with a 401, the error handler doesn't actually modify the distribution account status on the tenant because the condition for the tenant status is incorrect (we don't actually set the status to `TENANT_ACTIVATED` via the FE) so no tenant is selected. This fix changes the query so that it will attempt to select the tenant ~~as long as the tenant itself is not deactivated~~ regardless of tenant status.
bug fix for release
configured w/ a RW key
tenant distribution account is set to active in the db
```
605ca84b-9b5b-4416-996f-4b92a5ef37d4	bluecorp	http://bluecorp.stellar.local:8000	http://bluecorp.stellar.local:3000	TENANT_PROVISIONED	2024-07-23 17:40:26.169097+00	2024-07-23 18:20:12.398806+00		FALSE		DISTRIBUTION_ACCOUNT.CIRCLE.DB_VAULT	ACTIVE
``` …
=> [Fix][SDP-1274] Deactivate distribution acc when Circle API  returns 401

internal/circle/client.go, internal/circle/client_test.go
Adding basic retry for Circle 429 retries
Circle requests in Sandbox environment usually fail after 6 requests. With this change we can finish processing all the payments in a disbursement. 
* 🚨 Current implementation holds the database session until a retry is completed. In the case of Sandbox, that means the session is held for 5 minutes before the payment status is committed to the database. 
[`demo`]: …
=> [SDP-1276] Add retry for circle 429 requests

internal/scheduler/scheduler.go
`LogAndReportErrors` was being called with an empty error object, rather than the correct one.
Also, use the existing context rather than an empty one.
The error being [reported to Sentry](https://stellarorg.sentry.io/issues/5281895250/?project=4505189092556800&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=0) would be empty.
[`demo`]: …
=> SDP-1239: bug fix to select the correct error object used in a `LogAndReportErrors` call

internal/serve/httphandler/disbursement_handler_test.go, internal/serve/httphandler/update_receiver_handler.go, internal/serve/httphandler/update_receiver_handler_test.go, internal/serve/validators/disbursement_instructions_validator.go, internal/serve/validators/disbursement_instructions_validator_test.go, internal/serve/validators/receiver_registration_validator.go, internal/serve/validators/receiver_registration_validator_test.go, internal/serve/validators/receiver_update_validator.go, internal/serve/validators/receiver_update_validator_test.go, internal/serve/validators/validator.go, internal/serve/validators/validator_test.go, internal/utils/validation.go, internal/utils/validation_test.go
* Extract validation for receiver verification fields and make it consistent between disbursement instructions and patching receivers 
* Validate a receiver exists before patching them. 
* https://stellarorg.atlassian.net/browse/SDP-1283 …
=> SDP-1283 Make PATCH /receivers/:id validation consistent

db/migrations/sdp-migrations/2024-07-29.0-add-verification-type-year-month.sql, internal/data/disbursements.go, internal/data/receiver_verification_test.go, internal/serve/httphandler/disbursement_handler_test.go, internal/serve/httphandler/receiver_handler_test.go, internal/serve/httphandler/update_receiver_handler.go, internal/serve/httphandler/update_receiver_handler_test.go, internal/serve/httphandler/verifiy_receiver_registration_handler_test.go, internal/serve/publicfiles/js/receiver_registration.js, internal/serve/validators/disbursement_instructions_validator.go, internal/serve/validators/disbursement_instructions_validator_test.go, internal/serve/validators/disbursement_request_validator.go, internal/serve/validators/disbursement_request_validator_test.go, internal/serve/validators/receiver_registration_validator.go, internal/serve/validators/receiver_registration_validator_test.go, internal/serve/validators/receiver_update_validator.go, internal/utils/validation.go, internal/utils/validation_test.go
Add `YEAR_MONTH` as a verification type.
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/externalsecrets-common-previews.yaml#L241-L346
[`dev …
=> [SDP-1282] Add `YEAR_MONTH` as a verification type

internal/events/message.go, internal/events/message_test.go, internal/serve/httphandler/payments_handler.go, internal/serve/httphandler/payments_handler_test.go, internal/serve/httphandler/verifiy_receiver_registration_handler.go, internal/serve/httphandler/verifiy_receiver_registration_handler_test.go, internal/serve/serve.go, internal/services/disbursement_management_service.go
* Submit `paymentReadyToPay` to Circle topic for Registration and Retry 
* Have a unified way of submitting this message to avoid future errors
* The change introduced in https://github.com/stellar/stellar-disbursement-platform-backend/pull/371 only switches this topic for submitting events when disbursement starts. There are two other scenarios that were missed. 
[TODO or N/A]
[`demo`]: …
=> [SDP-1287] PaymentReadyToPay for Circle not submitted to correct topic

stellar-multitenant/internal/httphandler/tenants_handler.go
Add tenant provisioning error details to API response for better debugging experience
```
Server response: {
"error": "Could not generate SDP UI URL",
"extras": {
"error_details": "base URL must have at least two domain parts localhost:3000"
}
}
```
```
Server response: {
"error": "Could not generate SDP UI URL",
"extras": {
"error_details": "base URL must have at least two domain parts localhost:3000"
}
}
```
```
Server response: {
"error": "Could not provision a new tenant",
"extras": {
"error_details": "provisioning error: database schema creation for tenant failed: creating tenant redcorp database schema: creating schema for tenant sdp_redcorp: pq: schema \"sdp_redcorp\" already exists"
}
}
``` …
=> [Chore] Add tenant provisioning error details to response 

.github/workflows/anchor_platform_integration_check.yml, .github/workflows/ci.yml, .github/workflows/e2e_integration_test.yml, .github/workflows/singletenant_to_multitenant_db_migration_test.yml, dev/docker-compose-tss.yml, dev/main.sh, internal/data/disbursement_instructions.go, internal/integrationtests/docker/docker-compose-e2e-tests.yml, internal/integrationtests/scripts/e2e_integration_test.sh, internal/integrationtests/scripts/singletenant_to_multitenant_db_migration_test.sh, internal/serve/httphandler/disbursement_handler.go, internal/serve/serve.go, v1_compatibility/database_migration_compatibility.sh
Replace usage of `docker-compose` with `docker compose` in the CI workflows and the `*.sh` scripts.
`docker-compose`, AKA Compose V1, stopped receiving updates on July 2023 and the [Docker official documentation says](https://docs.docker.com/compose/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2) it should be replaced by `docker compose`, AKA Compose V2:
Sinde the versions of our CI actions were updated by dependabot, our CI jobs that used docker-compose started failing, surfacing the problem now that the latest docker versions stopped supporting docker-compose.
[`pr-preview`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/stellar-disbursement-platform/b …
=> [SDP-1292] Replace usage of `docker-compose` with `docker compose`

db/migrations/sdp-migrations/2024-08-17.0-organizations-message-channel-priority.sql, internal/data/organizations.go, internal/data/organizations_test.go, internal/message/aws_ses_client_test.go, internal/message/message.go, internal/message/message_dispatcher.go, internal/message/message_dispatcher_test.go, internal/message/message_test.go, internal/message/mock_message_dispatcher_interface.go, internal/scheduler/jobs/send_receiver_wallets_sms_invitation_job_test.go, internal/serve/httphandler/profile_handler.go, internal/serve/httphandler/profile_handler_test.go, internal/serve/httphandler/receiver_send_otp_handler.go, internal/serve/httphandler/receiver_send_otp_handler_test.go, internal/services/send_receiver_wallets_invite_service.go, internal/services/send_receiver_wallets_invite_service_test.go
* add `message_channel_priority` to `organizations` table 
* add trigger to validate the channel priority 
* modify `SendMessage` in `MessageDispatcher` to incorporate channel priority
* add ability to handle both `sms` and `e-mail` when messaging receivers. 
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/demo/demo- …
=> [SDP-1297] Add message channel priority to organizations table

db/migrations/sdp-migrations/2024-08-20.0-alter-receiver-verifications-table-add-verification-channel.sql, internal/data/receiver_verification.go, internal/data/receiver_verification_test.go, internal/data/receivers.go, internal/serve/httphandler/verifiy_receiver_registration_handler.go, internal/serve/httphandler/verifiy_receiver_registration_handler_test.go, internal/utils/utils.go
* database migration
* All already registered receivers should be updated with their verification field to phone_number, so we don’t lose any data
* Update the code to include that field when verifying the receiver wallet
* https://stellarorg.atlassian.net/browse/SDP-1307
[TODO or N/A]
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbu …
=> [SDP-1307] track verification channel

cmd/serve.go, dev/README.md, dev/docker-compose-monitoring.yml, dev/docker-compose-sdp-anchor.yml, dev/grafana/datasource.yaml, dev/prometheus/prometheus.yml, internal/circle/client.go, internal/circle/client_test.go, internal/circle/service.go, internal/circle/service_test.go, internal/dependencyinjection/circle_service_test.go, internal/monitor/main.go, internal/monitor/metric_tags.go, internal/monitor/monitor_labels.go, internal/monitor/prometheus_client.go, internal/monitor/prometheus_client_test.go, internal/monitor/prometheus_metrics.go, internal/monitor/utils.go, internal/serve/httphandler/circle_config_handler.go, internal/serve/httphandler/circle_config_handler_test.go, internal/serve/serve.go, resources/grafana/dashboard.json
* Added Metrics for Circle requests 
* Added optional docker containers for starting Prometheus and Grafana 
* Configured Grafana with the prometheus Data source 
* Removed fixed IDs from the Grafana dashboard and added new panels for monitoring Circle 
* Added Golang Metrics  
Monitor Requests made to the Circle API and detect any latency issues. 
[TODO or N/A]
[`demo`]: …
=> [SDP-1203] Add Circle Metrics

internal/data/fixtures.go, internal/message/message_dispatcher.go, internal/message/message_dispatcher_test.go, internal/message/mock_message_dispatcher_interface.go, internal/scheduler/jobs/send_receiver_wallets_sms_invitation_job_test.go, internal/serve/httphandler/receiver_send_otp_handler.go, internal/serve/httphandler/receiver_send_otp_handler_test.go, internal/services/send_receiver_wallets_invite_service.go, internal/services/send_receiver_wallets_invite_service_test.go
* Change send invitation scheduler job to work with SMS and Email. 
https://stellarorg.atlassian.net/browse/SDP-1316
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespace …
=> [SDP-1316] Update send and auto-retry invitation scheduler job to work with both SMS and email

internal/htmltemplate/htmltemplate.go, internal/htmltemplate/htmltemplate_test.go
Change `text/template` to `html/template`. 
Using the `html/template` package in Go instead of `text/template` package automatically escapes HTML special characters, preventing XSS attacks. …
=> [SDP-1343] HTML Injection Vulnerability

internal/htmltemplate/htmltemplate.go, internal/htmltemplate/htmltemplate_test.go, internal/message/aws_ses_client.go
When testing this with AWS SES, it looked like the whole email was escaped. In order to resolve this, we need to mark the HTML part of the template as safe by wrapping it with `template.HTML`  …
=> [SDP-1343] Fix HTML escaping for emails

dev/main.sh
1. Added quick checks for required system commands
2. Added quick check for required /etc/hosts records
Small checks like this can assist users new to the toolchain, who might feel confused and overwhelmed when things break in unexpected places. 
N/A
* n/a -- This PR adds tests for the new functionality or fixes.
* n/a -- Does the deployment work after merging?
[`demo`]: …
=> fix: #421 Enhance onboarding safety checks

stellar-auth/pkg/auth/auth.go, stellar-auth/pkg/auth/jwt_manager.go, stellar-auth/pkg/auth/jwt_manager_test.go
Increase token refresh window.
It was too short and causing the session to expire very often. We're changing it with this frontend change, where we add a token refresher to the frontend codebase. …
=> [SDP-1355] increase token refresh window

db/migrations/sdp-migrations/2024-10-18.0-update-default-value-of-otp-message-template.sql, internal/data/organizations.go, internal/data/organizations_test.go, internal/serve/httphandler/profile_handler_test.go, internal/serve/httphandler/receiver_send_otp_handler_test.go
Remove the word `phone` from the default organization's otp_message_template
Since we now allow email as a form of delivery of the OTP,
This PR addresses https://stellarorg.atlassian.net/browse/SDP-1339. …
=> [SDP-1339] Remove the word `phone` from the default organization's otp_message_template

internal/integrationtests/utils.go, internal/integrationtests/utils_test.go
Add path validation to the readDisbursementCSV method used in integration tests
Address https://stellarorg.atlassian.net/browse/SDP-1364.
[TODO or N/A]
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937 …
=> [SDP-1364] Add path validation to the readDisbursementCSV method used in integration tests

.github/workflows/e2e_integration_test.yml, cmd/integration_tests.go, cmd/utils/custom_set_value.go, cmd/utils/custom_set_value_test.go, db/migrations/admin-migrations/2024-07-15.0-migrate-data-v1-to-v2-function.sql, db/migrations/sdp-migrations/2024-10-31.0-disbursement-add-registration-contact-type.sql, dev/migrate_1.1.6_to_2.0.0.sh, internal/data/disbursements.go, internal/data/disbursements_test.go, internal/data/fixtures.go, internal/data/payments.go, internal/data/registration_contact_type.go, internal/integrationtests/integration_tests.go, internal/integrationtests/scripts/e2e_integration_test.sh, internal/integrationtests/server_api.go, internal/integrationtests/server_api_test.go, internal/integrationtests/utils.go, internal/serve/httphandler/disbursement_handler.go, internal/serve/httphandler/disbursement_handler_test.go, internal/serve/httphandler/payments_handler.go, internal/serve/httphandler/payments_handler_test.go, internal/serve/httphandler/registration_contact_types.go
Update `POST /disbursements` and `GET /disbursements` APIs to persist and return the Registration Contact Type
Address https://stellarorg.atlassian.net/browse/SDP-1370
Under the common interest of merging this PR quickly, I'll address the following tasks in a future PR:
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform …
=> [SDP-1370] Update `POST /disbursements` and `GET /disbursements` APIs to persist and return the Registration Contact Type

db/migrations/sdp-migrations/2024-11-01.1-disbursement-make-verification-field-nullable.sql, internal/data/disbursements.go, internal/data/disbursements_test.go, internal/serve/httphandler/disbursement_handler.go, internal/serve/httphandler/disbursement_handler_test.go, internal/utils/sql.go
Allow disbursement.verification_field to be empty
Address https://stellarorg.atlassian.net/browse/SDP-1380
[TODO or N/A]
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/names …
=> [SDP-1380] Allow disbursement.verification_field to be empty

internal/data/disbursement_instructions.go, internal/data/disbursement_instructions_test.go, internal/data/disbursements_test.go, internal/data/fixtures.go, internal/data/fixtures_test.go, internal/data/receivers_wallet.go, internal/data/receivers_wallet_test.go, internal/serve/httphandler/disbursement_handler.go, internal/serve/httphandler/disbursement_handler_test.go, internal/serve/validators/disbursement_instructions_validator.go, internal/serve/validators/disbursement_instructions_validator_test.go
Add support for Known Wallet Address processing when posting disbursement instructions. 
Support Known wallet addresses
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namesp …
=> [SDP-1374] Integrate Wallet Address in Processing Disbursement Instructions

internal/serve/httphandler/disbursement_handler.go, internal/serve/httphandler/disbursement_handler_test.go, internal/serve/httphandler/profile_handler.go, internal/serve/httphandler/profile_handler_test.go, internal/utils/validation.go, internal/utils/validation_test.go
Prevent user from setting a custom invite template with JS or HTML
Address https://stellarorg.atlassian.net/browse/SDP-1364
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/na …
=> [SDP-1364] Prevent user from setting a custom invite template with JS or HTML

.github/workflows/e2e_integration_test.yml, .github/workflows/singletenant_to_multitenant_db_migration_test.yml
Run e2e tests workflow only prior to publishing Docker images.
The PRs are taking too long to have their e2e tests approved, and we don't really need this being executed on every PR.
Also, due to the sequence number this cannot be parallelized, which leads to this workflow failing when running in parallel PRs.
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev …
=> [SDP-1430] Run e2e tests workflow only prior to publishing Docker images

cmd/integration_tests.go, internal/integrationtests/docker/docker-compose-e2e-tests.yml, internal/integrationtests/utils.go, internal/integrationtests/utils_test.go, internal/integrationtests/validations.go, internal/integrationtests/validations_test.go
Support xlm in integration tests
It's a good practice to support it, and it was needed to test e2e on futurenet
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/com …
=> [Fix] support XLM in integration tests

db/migrations/auth-migrations/2024-11-29.0-sanitize-email-auth_users-table.sql, stellar-auth/pkg/auth/auth.go, stellar-auth/pkg/auth/auth_test.go, stellar-auth/pkg/auth/authenticator.go, stellar-auth/pkg/auth/authenticator_test.go, stellar-auth/pkg/auth/fixtures.go, stellar-auth/pkg/auth/manager.go, stellar-auth/pkg/auth/manager_test.go, stellar-auth/pkg/cli/add_user.go, stellar-auth/pkg/cli/add_user_test.go
- Change persistence and Validation for emails to be case-insensitive for dashboard users
- Avoid login / forgot password validation errors due to case-sensitivity.  …
=> [SDP-1311] Make Dashboard User E-mails case insensitive 

internal/data/dibursements_state_machine.go, internal/data/disbursement_instructions.go, internal/data/disbursements.go, internal/data/disbursements_test.go, internal/data/payments.go, internal/serve/httphandler/disbursement_handler.go, internal/serve/httphandler/disbursement_handler_test.go, internal/serve/serve.go, internal/serve/serve_test.go
Add `DELETE /disbursements/:id` endpoint.
Ability to delete disbursements in `Ready` and `Draft` state.
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-prev …
=> [SDP-1234] DELETE disbursement in draft or ready status

internal/data/assets.go, internal/data/disbursements.go, internal/data/disbursements_test.go, internal/data/fixtures.go, internal/data/query_params.go, internal/data/registration_contact_type.go, internal/data/wallets.go, internal/serve/httphandler/export_handler.go, internal/serve/httphandler/export_handler_test.go, internal/serve/serve.go, internal/serve/serve_test.go, internal/services/disbursement_management_service.go
- Add a new endpoint `GET /exports/disbursements` 
Returned CSV : 
```csv
ID,Name,Wallet.Name,Asset.Code,Asset.Issuer,Status,VerificationField,CreatedAt,UpdatedAt,RegistrationContactType,TotalPayments,SuccessfulPayments,FailedPayments,CanceledPayments,RemainingPayments,AmountDisbursed,TotalAmount,AverageAmount
68494ca8-4f49-4d56-af81-42589963293c,WA_XLM,User Managed Wallet,XLM,,COMPLETED,,2024-11-28T22:31:24.722812Z,2024-11-28T22:31:36.441927Z,EMAIL_AND_WALLET_ADDRESS,1,1,0,0,0,0.12,0.12,0.12
9427421d-9540-4942-85c0-a2de2a45de31,WA_XLM_@,User Managed Wallet,XLM,,COMPLETED,,2024-11-28T22:34:44.172295Z,2024-11-28T22:34:52.497641Z,EMAIL_AND_WALLET_ADDRESS,1,1,0,0,0,0.12,0.12,0.12
```
- Add ability to export disbursements in CSV
[`pr-preview`]: …
=> [SDP-1259] Export Disbursements with Filters

internal/data/payments.go, internal/data/payments_test.go, internal/serve/httphandler/assets_handler_test.go, internal/serve/httphandler/export_handler.go, internal/serve/httphandler/export_handler_test.go, internal/serve/httphandler/payments_handler.go, internal/serve/serve.go, internal/serve/serve_test.go, internal/services/disbursement_management_service.go
Add a new endpoint to export payments with filtering 
`GET /exports/payments?sort=created_at&direction=asc&status=success`
**File name:** `payments_2024-12-12-14-51-41.csv`
```csv
ID,Amount,StellarTransactionID,Status,Disbursement.ID,Asset.Code,Asset.Issuer,Wallet.Name,Receiver.ID,ReceiverWallet.Address,ReceiverWallet.Status,CreatedAt,UpdatedAt,ExternalPaymentID,CircleTransferRequestID
3e01fae9-a6b7-41c2-b713-d8894603dfc3,0.1200000,be5760ce9b6ac91421ee896675e453daff0deced3aa852d48521ccced59f28f4,SUCCESS,68494ca8-4f49-4d56-af81-42589963293c,XLM,,User Managed Wallet,d37031d2-8bf4-41bb-8ce5-bf59075cdf8e,GDAKY4LJVM4TJDZWUCX4TAABRRPD5A53DAJ4VULG3QSAHQLWL2YNSZQJ,REGISTERED,2024-11-28T22:31:24.733382Z,2024-11-28T22:31:36.441927Z,PAY_01, …
```
=> [SDP-1391] Export Payments with Filtering

internal/data/circle_recipient.go, internal/data/circle_recipient_test.go, internal/serve/httphandler/payments_handler.go, internal/serve/httphandler/payments_handler_test.go, internal/services/paymentdispatchers/circle_payment_dispatcher.go, internal/services/paymentdispatchers/circle_payment_dispatcher_test.go
Errors in the POST /recipient endpoint are not being properly handled. What;s missing?
- When POST /recipient fails with `ErrCircleRecipientCreationFailedTooManyTimes`, we update the payments table with the failed status explaining the reason.
- When a payment that failed due to recipient creation issues is retried, the recipient is reset with `status=NULL` and `sync_attempts=0`.
- The method `ensureRecipientIsReady` was split into different sub-methods for better modularity and clarity, as suggested in https://github.com/stellar/stellar-disbursement-platform-backend/pull/486#discussion_r1878843074.
To wrap up https://stellarorg.atlassian.net/browse/SDP-1397
[`pr-preview`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e9884 …
=> [SDP-1397] Circle Payouts pt2: error handling & retries

internal/anchorplatform/sep24_auth_middleware.go, internal/anchorplatform/sep24_auth_middleware_test.go
Fix default tenant resolution during SEP24 registration. 
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/externalsecrets-common-previews.yaml#L241 …
=> [SDP-1460] Fix single tenant mode SEP24

db/migrations/sdp-migrations/2025-01-15.0-circle-recipient-new-status.sql, internal/circle/client.go, internal/data/circle_recipient.go, internal/services/paymentdispatchers/circle_payment_dispatcher.go, internal/services/paymentdispatchers/circle_payment_dispatcher_test.go
Workaround for Circle's bug where retries are not handled correctly when a trustline is missing.
A new error was detected in the Circle API that was not there in December: after the Circle payment to a recipient fails, that Recipient seems to be put in a burned/unusable state. This needs further investigation
1. Get a Stellar account that exists in the network but doesn't have the USDC trustline
2. Create a Stellar recipient on Circle (`POST /v1/addressBook/recipients`) using that address
3. Wait until the recipient status is updated to `active` in the Circle API
4. Send a payout to that receiver
5. The payout gets updated from `pending` to `failed`
6. If I submit the same payload again (with same `idempotency_key`) I get an API error `{code=5003, message=Inactive destination address, …
=> [SDP-1459] workaround for Circle's bug where retries are not handled correctly when a trustline is missing

internal/serve/httphandler/forgot_password_handler.go, internal/serve/httphandler/forgot_password_handler_test.go, internal/serve/httphandler/login_handler.go, internal/serve/httphandler/login_handler_test.go, internal/serve/httphandler/mfa_handler.go, internal/serve/httphandler/mfa_handler_test.go, internal/serve/httphandler/profile_handler.go, internal/serve/httphandler/reset_password_handler.go, internal/serve/httphandler/reset_password_handler_test.go, internal/serve/httphandler/verify_receiver_registration_handler_test.go, internal/serve/validators/query_validator.go, internal/serve/validators/validator.go, internal/serve/validators/validator_test.go, stellar-auth/pkg/auth/auth.go, stellar-auth/pkg/auth/auth_test.go, stellar-auth/pkg/auth/manager.go, stellar-auth/pkg/auth/mocks.go, stellar-auth/pkg/cli/add_user.go, stellar-auth/pkg/utils/password_validation.go, stellar-auth/pkg/utils/password_validation_test.go
Prepare code for API-only usage by reorganizing the reCaptcha and MFA sections in the handlers they're being used.
Since the MFA and reCAPTCHA enforcers were being used in different places for different handlers, it wasn't easy to modularize their usage. By streamlining their usage, the code becomes easier to adapt and make it optional.
Add a way to bypass them through IP filering.
[`demo`]: …
=> [SDP-1247] Prepare code for API-only usage by reorganizing the reCaptcha and MFA sections in the handlers they're being used

db/migrations/sdp-migrations/2025-01-24.0-track-who-confirmed-receiver-verification-info.sql, internal/data/disbursement_instructions_test.go, internal/data/receiver_verification.go, internal/data/receiver_verification_test.go, internal/serve/httphandler/update_receiver_handler.go, internal/serve/httphandler/update_receiver_handler_test.go, internal/serve/httphandler/verify_receiver_registration_handler.go
Allow patching already confirmed verification fields
Some receivers got locked out from a partner's system and this seems to be the most reliable fix.
@marwen-abid added an audit table in #513 that will be used to keep track of such changes.
=> [SDP-1523] allow patching already confirmed verification fields

db/migrations/sdp-migrations/2025-01-28.0-add-audit-to-receivers-table.sql, internal/data/receiver_verification_audit_test.go, internal/data/receivers_audit_test.go, stellar-multitenant/internal/httphandler/tenants_handler_test.go, stellar-multitenant/internal/provisioning/manager_test.go
- add auditing for `receivers` table
- add unit tests for `receivers_audit` and `receiver_verification_audit` 
- track changes in critical tables. 
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e9 …
=> [SDP-1304] Add audit receivers and unit tests

internal/data/payments.go, internal/data/payments_test.go, internal/serve/httphandler/disbursement_handler_test.go, internal/serve/httphandler/payments_handler_test.go
Implement `q={term}` in the `GET /payments` endpoint. It queries for the fields `p.id`, `p.external_payment_id`, `rw.stellar_address`, `d.name`.
Address the BE part of https://stellarorg.atlassian.net/browse/SDP-1535
[`pr-preview …
=> [SDP-1535] Update the `GET /payments` endpoint to accept `q={term}` query searches

internal/data/disbursements.go, internal/data/disbursements_test.go, internal/data/payments_state_machine.go, internal/data/receivers_test.go, internal/services/circle_reconciliation_service.go, internal/services/circle_reconciliation_service_test.go
- Complete Circle Disbursements when all payments reach a terminal state. 
- Payment Terminal State = `SUCCESS` or `CANCELED` . 
Note: `FAILED` isn't considered terminal because it's retriable. 
- Bugfix: Circle Disbursements weren't getting terminated. 
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/demo/demo-backe …
=> [SDP-1537] Complete Circle Disbursements during Reconciliation

CHANGELOG.md, internal/serve/httphandler/disbursement_handler_test.go, internal/services/disbursement_management_service.go, internal/services/disbursement_management_service_test.go, stellar-auth/pkg/auth/auth.go, stellar-auth/pkg/auth/auth_test.go, stellar-auth/pkg/auth/authenticator.go, stellar-auth/pkg/auth/authenticator_test.go, stellar-auth/pkg/auth/mocks.go
Resolve all users (active and inactive) when decorating GET /disbursements data.
Get Disbursements fails when user deactivated
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev …
=> [SDP-1545] Get Disbursements fails when user deactivated

db/db.go, internal/data/disbursement_instructions.go, internal/data/disbursement_instructions_test.go, internal/data/disbursements.go, internal/data/disbursements_test.go, internal/data/fixtures.go, internal/serve/httperror/httperror.go, internal/serve/httphandler/assets_handler_test.go, internal/serve/httphandler/disbursement_handler.go, internal/serve/httphandler/disbursement_handler_test.go, internal/serve/httphandler/forgot_password_handler.go, internal/serve/httphandler/forgot_password_handler_test.go, internal/serve/httphandler/payments_handler_test.go, internal/services/disbursement_management_service_test.go, internal/services/setup_wallets_for_network_service_test.go, internal/transactionsubmission/store/channel_transaction_bundle_test.go, stellar-auth/pkg/auth/authenticator_test.go
I separated the refactors into their own commits to make review easier. 
Change `POST /disbursements` 
* if only fields are sent, works the same as nowadays
* 👋 (new*) if fields + file are sent, then process the request as `ATOMIC{POST payload + POST instructions}`
* Improve user experience when creating disbursements. 
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/k …
=> [DEV-1534] Make create disbursement atomic

internal/data/receivers_test.go, internal/message/aws_ses_client_test.go, internal/message/message_test.go, internal/message/twilio_sendgrid_client_test.go, internal/serve/httphandler/receiver_send_otp_handler_test.go, internal/serve/httphandler/user_handler.go, internal/serve/httphandler/user_handler_test.go, internal/serve/validators/receiver_registration_validator_test.go, internal/utils/string.go, internal/utils/validation.go, internal/utils/validation_test.go, stellar-auth/pkg/auth/authenticator.go, stellar-auth/pkg/auth/authenticator_test.go, stellar-auth/pkg/utils/utils.go, stellar-auth/pkg/utils/utils_test.go
* Improve `POST /users` request validation. 
* `POST /users` was returning 500 instead of 400 in certain cases 
```
POST /users
{"first_name":"Marwen","last_name":" ","roles":["owner"],"email":"marwen@stellar.org"}
```
[`pr-preview …
=> [SDP-1553] - POST /users fails with 500 during validation errors.

internal/serve/httphandler/receiver_registration_handler.go, internal/serve/httphandler/receiver_registration_handler_test.go, internal/serve/httphandler/receiver_send_otp_handler.go, internal/serve/httphandler/receiver_send_otp_handler_test.go, internal/serve/httphandler/verify_receiver_registration_handler.go, internal/serve/httphandler/verify_receiver_registration_handler_test.go, internal/serve/serve.go
Added two fields to `/sep24-interactive-deposit/init` API: 
* `is_recaptcha_disabled` 
* `organization_logo` 
Added enforcement for `is_recaptcha_disabled` to `sep24-interactive-deposit` endpoints. 
Improve UX for SEP24 registration …
=> [SDP-1561] Add `organization_logo` and `is_recaptcha_disabled` to `/init` call

internal/serve/httphandler/profile_handler.go, internal/serve/httphandler/profile_handler_test.go, internal/serve/httphandler/receiver_registration_handler.go, internal/serve/httphandler/receiver_registration_handler_test.go, internal/serve/httphandler/receiver_send_otp_handler.go, internal/serve/httphandler/receiver_send_otp_handler_test.go, internal/serve/httphandler/verify_receiver_registration_handler.go, internal/serve/httphandler/verify_receiver_registration_handler_test.go, internal/serve/serve.go, internal/serve/serve_test.go
Change `GET /organization/logo` to not be authenticated. 
This call doesn't need to be authenticated. This will also help with displaying logo in SEP-24 flow.  …
=> [SDP-1561] Make `GET /organization/logo` unauthenticated 

CHANGELOG.md, internal/services/send_receiver_wallets_invite_service.go, internal/services/send_receiver_wallets_invite_service_test.go
Preserve port numbers in SEP-24 invitation links by replacing `.Hostname()` with `.Host`.
When testing the flow locally, including the ports is important to make sure it works end-to-end.
Assuming this would be opened by a frontend client running javascript/typescript, I tested the result is the expected through these steps:
```ts
// Assuming this is your URL
const url = "https://test.com?asset=FOO-GCKGCKZ2PFSCRQXREJMTHAHDMOZQLS2R4V5LZ6VLU53HONH5FI6ACBSX&domain=foo.bar%3A8000&name=Foo+Bar+Org"
// Create URLSearchParams object from the URL's query string
const searchParams = new URLSearchParams(new URL(url).search)
// Or get all parameters as an object
const allParams = Object.fromEntries(searchParams.entries())
// Result:
// {
//   asset: …
```
=> SDP-1501: Preserve port numbers in SEP-24 invitation links

.github/workflows/e2e_integration_test.yml, CHANGELOG.md, internal/circle/client.go
Change `{CIRCLE_API}/ping` method to validate only the response status code
It was validating the response body as well, but Circle inadvertently changed it and the API is not compliant with the documentation anymore. Since this is just a /ping endpoint, we don't need to enforce any specific body content.
=> SDP-1569: Change `{CIRCLE_API}/ping` method to validate only the response status code

CHANGELOG.md, cmd/channel_accounts_test.go, cmd/distribution_accounts_test.go, cmd/integration_tests_test.go, cmd/utils/shared_config_options.go, cmd/utils/test_helpers.go, internal/scheduler/jobs/patch_anchor_platform_transactions_job_test.go, internal/scheduler/jobs/send_receiver_wallets_sms_invitation_job_test.go, internal/services/patch_anchor_platform_transactions_completion.go, internal/services/patch_anchor_platform_transactions_completion_test.go, internal/utils/test_helpers.go
Fix CLI test assertions and improve DRY
Some CLI tests would fail due to different reasons from what was expected, and none of them was validating the output error message.
Also, there was a lot of code repetition for a kind of assertion that's not trivial.
=> SDP-1575: fix CLI test assertions and improve DRY

internal/serve/httphandler/receiver_registration_handler.go, internal/serve/httphandler/receiver_registration_handler_test.go
Return `recaptcha_site_key` in the `/sep24-interactive-deposit/init` body response.
With this change, the SEP-24 react application won't need to rely on the `.env` anymore.
=> SDP-1577: Return `recaptcha_site_key` in the `/sep24-interactive-deposit/init` body response

.github/workflows/assign-pr-author.yml, CHANGELOG.md
Add GH Workflow to automatically set the pull request assignee.
📈 Kaizen
=> Chore: Add GH Workflow to automatically set the pull request assignee

CHANGELOG.md, README.md, internal/serve/serve.go, internal/serve/serve_test.go
Remove the restriction that prevents disabling ReCAPTCHA in Pubnet deployments, as requested in [SDP-1597](https://stellarorg.atlassian.net/browse/SDP-1597).
We currently have safeguards in place that don't allow the option `DISABLE_RECAPTCHA=true` for Pubnet deployments. This PR allows disabling ReCAPTCHA in Pubnet environments while still maintaining the restriction on disabling MFA.
Instead of returning an error when ReCAPTCHA is disabled in Pubnet, the code now logs a warning message to ensure administrators are aware of the potential security implications.
[TODO or N/A]
[SDP-1597]: https://stellarorg.atlassian.net/browse/SDP-1597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SDP-1597 pubnet recaptcha disble allowed

CHANGELOG.md, internal/transactionsubmission/engine/signing/distribution_account_resolver.go, stellar-multitenant/pkg/tenant/manager.go, stellar-multitenant/pkg/tenant/manager_test.go, stellar-multitenant/pkg/tenant/mocks.go
Introduce a new method `GetTenantByIDIncludingDeactivated` for resolving distribution accounts for tenants.
Fetching distribution account fails when the tenant is deactivated. We should be able to fetch distribution account for deactivated tenants (not yet deleted). 
- [] Preview deployment works as expected
=> SDP-1631: Delete Tenant fails when Stellar Account is DB_VAULT

contracts/Cargo.lock, contracts/smart-wallet/Cargo.toml, contracts/smart-wallet/src/lib.rs, contracts/smart-wallet/src/test.rs, contracts/smart-wallet/src/webauthn.rs
This fixes how the `challenge` and `type` fields are extracted from the client data JSON. Instead of asking the user to provide the offsets of these fields, the client data JSON is parsed by `serde_json_core`.
Asking the client to provide the offsets can result in the user unintentionally authorizing transactions if the challenge offset provided is outside of the `challenge` field.
N/A
=> SDP-1616: Fix WebAuthn client_data_json field extraction

CHANGELOG.md, db/migrations/sdp-migrations/2025-04-30.0-create-api-keys-table.sql, internal/data/api_keys.go, internal/data/api_keys_test.go, internal/data/models.go, internal/serve/httphandler/api_key_handler.go, internal/serve/httphandler/api_key_handler_test.go, internal/serve/httphandler/assets_handler_test.go, internal/serve/middleware/middleware.go, internal/serve/serve.go, internal/serve/serve_test.go, stellar-multitenant/internal/httphandler/tenants_handler_test.go, stellar-multitenant/internal/provisioning/manager_test.go
This PR implements API key authentication for the SDP backend API. The implementation:
- Adds a new `api_keys` database table with audit support
- Creates the API key data model
- Implements the `POST /api-keys` endpoint for creating new API keys
- Adds support for granular permissions through a hierarchical permission system
- Provides IP address allowlisting
API keys follow a secure format `SDP_<random>` where only salted hashes are stored in the database. The full key is returned only once at creation time.
API keys provide an alternative authentication method to JWT tokens, this change enables:
- More granular access control through specific permissions
- Better security through IP address restrictions
- Audit trail for all API key operations
[TODO or N/A]
=> SDP-1625 add create API key endpoint

CHANGELOG.md, db/migrations/sdp-migrations/2025-05-18.0-receiver-wallets-add-status-message.sql, internal/data/fixtures.go, internal/data/receiver_verification_audit_test.go, internal/data/receiver_wallets_audit_test.go, internal/data/receiver_wallets_state_machine.go, internal/data/receiver_wallets_state_machine_test.go, internal/data/receivers_wallet.go, internal/data/receivers_wallet_test.go, internal/serve/httphandler/receiver_send_otp_handler_test.go, internal/serve/httphandler/receiver_wallets_handler.go, internal/serve/httphandler/receiver_wallets_handler_test.go, internal/serve/httphandler/verify_receiver_registration_handler.go, internal/serve/serve.go, internal/serve/serve_test.go, stellar-multitenant/internal/httphandler/tenants_handler_test.go, stellar-multitenant/internal/provisioning/manager_test.go
- Add a new endpoint `PATCH /receivers/wallets/:receiver-wallet-id/status` that allows for switching the status of a receiver-wallet. Currently, only path supported is `REGISTERED` -> `READY`, which means we're unregistering the receiver-wallet. We may later decide to also allow marking a wallet as flagged. 
- Allow users to unregister a wallet in order to force registration again.
=> SDP-1485: add API endpoint to unregistering a receiver wallet

internal/data/receivers_wallet.go, internal/data/receivers_wallet_test.go, internal/serve/httphandler/receiver_wallets_handler.go, internal/serve/httphandler/receiver_wallets_handler_test.go
- Prevent Unregistering User-Managed Wallets 
- Prevent Unregistering Receiver Wallets with payments in-progress. 
- In-Progress : [ Ready, Pending and Paused ]
- User Managed Wallets : Can't be re-registered for now. 
- Wallets with In-Progress payments : Prevent the SDP from fulfilling the payment.
=> SDP-1689: Prevent unregistering user-managed wallets and wallets with in-progress payments

CHANGELOG.md, helmchart/sdp/templates/02.2-deployment-ap.yaml
Turn on the service account in the helm chart for the ap deployment
Currently the serviceaccount name is commented out while all the other deployments have the serviceaccountname set up
[TODO or N/A]
=> Feat: Turn on service account use in the ap deployment in the helm chart

internal/transactionsubmission/wallet_creation_transaction_handler.go, internal/transactionsubmission/wallet_creation_transaction_handler_test.go
Fetch the account sequence number again after updating the transaction parameters.
It fails with a bad sequence number error, otherwise.
N/A
=> SDP-1614: Fix wallet creation transaction building

CHANGELOG.md, internal/data/assets.go, internal/data/assets_test.go, internal/data/fixtures.go, internal/data/wallets.go, internal/data/wallets_test.go, internal/serve/httphandler/wallets_handler.go, internal/serve/httphandler/wallets_handler_test.go
The `GET /wallets` endpoint now supports filtering wallets by the assets they support.
| Parameter | Type | Description | Example |
|-----------|------|-------------|---------|
| `supported_assets` | string | Comma-separated list of asset codes or IDs | `USDC,XLM` |
```http
GET /wallets?supported_assets=USDC,XLM
```
Returns wallets that support **both** USDC and XLM (AND logic).
- **Asset codes**: `USDC`, `XLM`, `EURC`
- **Asset IDs**: `550e8400-e29b-41d4-a716-446655440000`
- **Mixed**: `USDC,550e8400-e29b-41d4-a716-446655440000`
```http
GET /wallets?supported_assets=USDC
```
Returns all wallets that support USDC.
```http
GET /wallets?supported_assets=USDC,XLM
```
Returns only wallets that support **both** USDC **and** XLM.
```http
GET /wallets?supported_assets=USDC&enabled=true
``` …
=> SDP-1728: Add `supported_assets` filter to `GET /wallets`

.github/workflows/e2e_integration_test.yml, internal/integrationtests/scripts/e2e_integration_test.sh, internal/integrationtests/scripts/singletenant_to_multitenant_db_migration_test.sh
The SDP images were updated to use golang:1.24.2-alpine, which does not include `bash`, causing the e2e tests to fail with 
```
Run docker exec e2e-sdp-api bash -c "./stellar-disbursement-platform integration-tests create-data"
OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown
```
Example: https://github.com/stellar/stellar-disbursement-platform-backend/actions/runs/15881981520/job/44864347506
This updates e2e workflows to use `sh` instead of `bash`.
Fix e2e tests.
N/A
=> Fix: Use `sh` instead of `bash` in e2e tests

db/migrations/sdp-migrations/2025-07-17.0-add-receiver-contact-index-to-embedded-wallets.sql, internal/data/embedded_wallet.go, internal/serve/httphandler/wallet_creation_handler.go, internal/serve/httphandler/wallet_creation_handler_test.go, internal/serve/serve.go, internal/serve/serve_test.go, internal/services/embedded_wallet_service.go, internal/services/embedded_wallet_service_test.go, internal/services/mocks/embedded_wallet_service.go, internal/services/send_receiver_wallets_invite_service.go, internal/services/send_receiver_wallets_invite_service_test.go
This implements the `/embedded-wallets/resend-invite` endpoint, which allows wallets to resend invitations to receivers who have not set up their wallets.
Need to resend invitation emails for the demo.
N/A
=> SDP-1736: Implement invite resend API for embedded wallets

internal/serve/httphandler/wallet_creation_handler.go, internal/serve/httphandler/wallet_creation_handler_test.go
This checks that the `public_key` is a valid P256 public key.
We want to avoid invalid public keys before a transaction is created in TSS.
N/A
=> Fix: Validate wallet public_key more thoroughly

db/migrations/sdp-migrations/2025-07-19.0-add-html-email-template-support.sql, internal/data/organizations.go, internal/data/organizations_test.go, internal/htmltemplate/htmltemplate.go, internal/htmltemplate/htmltemplate_test.go, internal/serve/httphandler/profile_handler.go, internal/serve/httphandler/profile_handler_test.go, internal/services/send_receiver_wallets_invite_service.go, internal/services/send_receiver_wallets_invite_service_test.go, internal/utils/validation.go, internal/utils/validation_test.go
This implements organization customization for receiver invites with custom HTML.
We want to send custom HTML/CSS emails for the demo
Tested locally without actually sending it with Amazon SES or Sendgrid.
=> SDP-1736: Implement org level HTML invite customization

internal/serve/serve.go
Grants access to all roles for the embedded wallet APIs so that it's accessible by API
Not currently accessible by API since it's limited to the financial controller role.
N/A
=> Fix: Allow access to embedded-wallet endpoints from BE

internal/services/send_receiver_wallets_invite_service.go, internal/services/send_receiver_wallets_invite_service_test.go
This updates the token generation process so that it only generates new tokens if the previous token is in the FAILED status.
This fixes a bug where a new token is generated when a receiver creates a wallet successfully.
N/A
=> Fix: Only generate new wallet tokens if previous failed

db/migrations/sdp-migrations/2025-08-13.0-increase-credential-id-column-size.sql, internal/data/embedded_wallet.go, internal/data/embedded_wallet_test.go, internal/serve/httphandler/wallet_creation_handler.go, internal/serve/httphandler/wallet_creation_handler_test.go
This adds length validation on the `credential_id` of the create embedded wallet request, and extends the column length.
Valid credential IDs are up 1023 bytes.
N/A
=> Fix: Add `credential_id` request validation

internal/services/wallet_creation_from_submitter_service.go, internal/services/wallet_creation_from_submitter_service_test.go
When a wallet creation transaction fails during simulation, the distribution account is not assigned. This PR updates the sync job to only check this field when the transaction was successful.
Wallet creation sync job fails
N/A
=> Fix: Check wallet creation distribution account only when successful

internal/services/send_receiver_wallets_invite_service.go, internal/services/send_receiver_wallets_invite_service_test.go
This removes all parameters from the invite link when the provider is an embedded wallet.
Only the token parameter is used by the demo.
N/A
=> Remove extra parameters from invite link

CHANGELOG.md, dev/docker-compose-kafka.yml, internal/integrationtests/docker/docker-compose-e2e-tests.yml
Replace Bitnami Kafka Image with Apache Kafka official image
Bitnami discontinuing support for image.
=> SDP-1839: Replace Bitnami Kafka image with Apache Kafka official image

CHANGELOG.md, internal/serve/httphandler/receiver_handler.go, internal/serve/httphandler/receiver_handler_test.go, internal/serve/validators/receiver_validator.go
- Replace hardcoded `MemoTypeID` in  _receiver_handler_ with `schema.ParseMemo()`
- Replace the memo length check in _receiver_validator_ with `schema.ParseMemo()` 
- Add test coverage for memo type detection
=> SDP-1845: Parse correct memo type in receiver creation

cmd/utils/shared_config_options.go, helmchart/sdp/README.md, helmchart/sdp/values.yaml, internal/serve/httphandler/bridge_integration_handler.go, internal/serve/httphandler/receiver_wallets_handler.go, internal/utils/url.go, internal/utils/url_test.go
- Add defaults for `BRIDGE_BASE_URL` 
- Add validation for `BRIDGE_BASE_URL` 
- Surface message errors from Bridge 
- Make Bridge configuration clearer.
=> SDP-1853: Improve Bridge docs and defaults

cmd/auth.go, dev/docker-compose-sdp-anchor.yml, internal/message/message.go, internal/message/twilio_whatsapp_client.go, internal/message/twilio_whatsapp_client_test.go, internal/scheduler/jobs/send_receiver_wallets_sms_invitation_job_test.go, internal/serve/httphandler/forgot_password_handler.go, internal/serve/httphandler/login_handler.go, internal/serve/httphandler/receiver_send_otp_handler.go, internal/serve/httphandler/receiver_send_otp_handler_test.go, internal/serve/httphandler/user_handler_test.go, internal/services/send_invitation_message.go, internal/services/send_invitation_message_test.go, internal/services/send_receiver_wallets_invite_service.go, internal/services/send_receiver_wallets_invite_service_test.go
* Change ContentVariables in Twilio Whatsapp implementation to be numbered instead of named. 
* Numbered variables guarantee order during tokenization process
* Things worked up to now because we only have two parameters per message and changes of a mix-up are low. 
* Guarantee order.
=> SDP-1873: Use numbered Twilio ContentVariables instead of named to guarantee order

db/migrations/sdp-migrations/2025-05-18.1-create-embedded-wallet.sql, internal/data/embedded_wallet.go, internal/data/embedded_wallet_test.go, internal/data/fixtures.go, internal/services/embedded_wallet_service.go, internal/services/embedded_wallet_service_test.go
Persist the passkey's public key in the embedded wallets table so that it can be used to verify the WebAuthn challenge signed by the frontend.
Wallet authentication
N/A
=> SDP-1862: Add public key to embedded wallets table
