- internal/serve/httphandler/profile_handler.go
- internal/serve/httphandler/profile_handler_test.go
Add ID in the response of `GET /profile` endpoint. 
This change will support Approver function. 
[TODO or N/A]
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/comm …
> [SDP-812] feat: add ID to `GET /profile` 

- helmchart/sdp/Chart.yaml
Porting the following changes 
https://github.com/stellar/helm-charts/pull/60 
https://github.com/stellar/helm-charts/pull/61
https://github.com/stellar/helm-charts/pull/62
[TODO or N/A]
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-p …
> SDP-663 cleanup helm charts

- internal/data/payments.go
- internal/scheduler/jobs/payments_processor_job.go
- internal/scheduler/jobs/tss_monitor_job.go
- internal/scheduler/scheduler.go
- internal/services/send_payments_service.go
- internal/services/tss_monitor_service.go
* Reduced interval for TSS Monitor and Payment jobs to 10s 
* Removes some unnecessary logs
* Switched some logs from Info to Debug
* Added logs where needed. 
* Sync payment statuses faster 
* Make logs less verbose when not needed
[TODO or N/A]
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/demo/demo-backend-helm- …
> SDP-839 reduce job interval

- helmchart/sdp/README.md
- helmchart/sdp/minimal-values.yaml
- helmchart/sdp/values.yaml
Create a minimal-values.yaml helm file to document the minimum config needed to use SDP chart. 
[TODO or N/A]
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/commo …
> SDP-854 Create a `minimal-values.yaml` helm file

- cmd/db_test.go
- internal/data/assets.go
- internal/data/assets_test.go
- internal/data/fixtures.go
- internal/serve/httphandler/assets_handler.go
- internal/serve/httphandler/assets_handler_test.go
- internal/services/setup_wallets_for_network_service_test.go
- internal/services/wallets/wallets_pubnet.go
- internal/services/wallets/wallets_testnet.go
Add a new parameter to `GET /assets` to filter assets by wallet id. 
e.g. `GET/assets?wallet=360383c7-9e6a-4713-8293-9c3565877a0f` 
We added association between wallets and their supported assets. 
[TODO or N/A] …
> SDP-370 Filter assets by wallets

- internal/services/wallets/wallets_testnet.go
Change SEP10 domain for wallet initialization on testnet to `api-dev` instead of `api`. 
[TODO or N/A] …
> Change Sep10 domain for Vibrant to api-dev instead of api

- internal/services/send_receiver_wallets_invite_service.go
- internal/services/send_receiver_wallets_invite_service_test.go
Fix invitation link by sending "native" when the asset is the native one.
Also, allow XLM with an issuer, since the network allows that.
The examples in [SEP-24](https://github.com/stellar/stellar-protocol/blob/master/ecosystem/sep-0024.md#response-2) use code:native, so we'll follow the same pattern here.
Also, assets with code XLM and a non-empty issuer are allowed in the network, so I enabled it here too.
[TODO or N/A]
[`dev`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/backe …
> SDP-885: fix invitation link by sending `native` when the asset is the native one

- internal/serve/httphandler/receiver_send_otp_handler.go
- internal/serve/serve.go
This PR fixes the endpoint HTTP method to patch wallets.
The HTTP method should be `PATCH` and not `POST`.
N/A
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/comm …
> serve: fix wallets endpoint HTTP method

- cmd/db_test.go
- internal/services/setup_wallets_for_network_service_test.go
- internal/services/wallets/wallets_pubnet.go
This is a change we needed to make when deploying SDP to prd (mainnet). 
[TODO or N/A]
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/externalsecr …
> add vibrant rc pubnet to list of supported wallets

- dev/README.md
This section isn't needed and doesn't exist in the public docs. Removing this from the sdp-backend docs. 
[TODO or N/A]
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namesp …
> doc: remove unnecessary hosts section in quick start

- CHANGELOG.md
- helmchart/sdp/Chart.yaml
- main.go
> Release 1.0.0 into develop (SDP-902)

- dev/docker-compose-tss.yml
Delete all channel accounts on startup
When the distribution key is changed, the existing channel accounts would no longer be valid. Upon restart of the tss, we should delete all accounts _in case_ the distribution account was changed which is a trivial action. 
[TODO or N/A]
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-pl …
> [SDP-942] [TSS] Stale channel account not cleared after switching distribution keys 

- .github/workflows/docker_image_public_release.yml
build and release a docker image for `sdp-multitenant` branch. 
This docker image will be used for docker-compose and for multi-tenant integration environments. 
[TODO or N/A] …
> SDP-920 Deploy a docker image for MTN

- internal/services/wallets/wallets_pubnet.go
Add support for the Freedom Wallet.
Freedom Wallet is already being used in Gambia to allow communites to receive SDP disbursements, it would be great to have it listed as one of the wallets.
[TODO or N/A] …
> wallets - Add Freedom Wallet

- cmd/serve.go
- helmchart/sdp/Chart.yaml
- helmchart/sdp/templates/01.1-configmap-sdp.yaml
- helmchart/sdp/templates/01.3-configmap-tss.yaml
- helmchart/sdp/templates/02.1-deployment-sdp.yaml
- helmchart/sdp/templates/02.3-deployment-tss.yaml
- helmchart/sdp/templates/04.1-ingress-sdp.yaml
- helmchart/sdp/templates/04.3-ingress-dashboard.yaml
- helmchart/sdp/templates/05.3-secrets-tss.yaml
- helmchart/sdp/templates/_helpers.tpl
- helmchart/sdp/values.yaml
Change helm charts to accommodate stellar multi-tenant deployment. 
Matching Kube PR: https://github.com/stellar/kube/pull/1850
Provision an environment for integrating multi-tenant work.
[TODO or N/A] …
> [SDP-920] multi-tenant dev instance deployment 

- dev/docker-compose.yml
Fix the main docker-compose file. 
The docker-compose file was failing to up the services because the Kafka service wasn't being referenced on the file.
N/A …
> dev: main docker-compose file

- internal/serve/serve.go
Add business role permission for `/receivers/{id}` endpoint
[TODO or N/A] …
> [SDP-1011] add user permission for the business role for receiver details

- .github/workflows/ci.yml
Use CI to make sure the helm README is up to date.
We sometimes forget to update it.
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/externalsecret …
> [SDP-853] Use CI to m sure the helm README is up to date

- CHANGELOG.md
- internal/htmltemplate/tmpl/receiver_register.tmpl
- main.go
Hot-fix: re-add missing recaptcha script to HTML template in the SEP24 registration flow.
It was removed in https://github.com/stellar/stellar-disbursement-platform-backend/pull/152. …
> Hot-fix: re-add missing recaptcha script to HTML template in the SEP24 registration flow

- CHANGELOG.md
- internal/data/assets.go
- internal/data/assets_test.go
- internal/serve/httphandler/disbursement_handler.go
- internal/serve/httphandler/receiver_send_otp_handler.go
- internal/serve/httphandler/receiver_send_otp_handler_test.go
- internal/serve/publicfiles/js/receiver_registration.js
- internal/services/disbursement_management_service.go
- internal/services/disbursement_management_service_test.go
- internal/transactionsubmission/utils/utils_test.go
- main.go
- SEP24 registration flow not working properly when the phone number was not found in the DB [#187](https://github.com/stellar/stellar-disbursement-platform-backend/pull/187)
- Fix distribution account balance validation that fails when the intended asset is XLM [#186](https://github.com/stellar/stellar-disbursement-platform-backend/pull/186)
[`demo`]: …
> Release 1.1.3 hotfix

- CHANGELOG.md
- internal/data/assets.go
- internal/data/assets_test.go
- internal/serve/httphandler/disbursement_handler.go
- internal/serve/httphandler/receiver_send_otp_handler.go
- internal/serve/httphandler/receiver_send_otp_handler_test.go
- internal/serve/publicfiles/js/receiver_registration.js
- internal/services/disbursement_management_service.go
- internal/services/disbursement_management_service_test.go
- internal/transactionsubmission/utils/utils_test.go
- main.go
- SEP24 registration flow not working properly when the phone number was not found in the DB [#187](https://github.com/stellar/stellar-disbursement-platform-backend/pull/187)
- Fix distribution account balance validation that fails when the intended asset is XLM [#186](https://github.com/stellar/stellar-disbursement-platform-backend/pull/186)
> Release 1.1.3 hotfix to develop (#188)

- CHANGELOG.md
- internal/data/assets.go
- internal/data/assets_test.go
- internal/serve/httphandler/disbursement_handler.go
- internal/serve/httphandler/receiver_send_otp_handler.go
- internal/serve/httphandler/receiver_send_otp_handler_test.go
- internal/serve/publicfiles/js/receiver_registration.js
- internal/services/disbursement_management_service.go
- internal/services/disbursement_management_service_test.go
- main.go
Please review that your changes were ported correctly. 
```
#	internal/data/assets.go
#	internal/data/assets_test.go
#	internal/services/disbursement_management_service.go
#	internal/services/disbursement_management_service_test.go
```
> [Merge] Merge `develop` into `sdp-multitenant`

- internal/serve/httphandler/assets_handler_test.go
Attempt to fix recurring false-negative in the test Test_AssetHandler_submitChangeTrustTransaction_makeSurePreconditionsAreSetAsExpected by walking away from a reflection comparison, which was done by using mock's `.Run` instead of `.MatchedBy` to assert the timebounds.
Errors like [this](https://github.com/stellar/stellar-disbursement-platform-backend/actions/runs/7792837546/job/21251914245#step:5:209) are false negatives that could be caused by reflection with complex objects.
By using Run rather than mock.MatchedBy, we avoid the reflection.
[`dev`]: …
> [Chore] attempt to fix recurring false-negative in tests by walking away from a reflection comparison in `assets_handler_test.go`

- go.list
- go.mod
- go.sum
- internal/services/disbursement_management_service.go
- internal/services/disbursement_management_service_test.go
Tickets: SDP-1102 & SDP-1103
- Add a filter to remove payments with assets different from the disbursement asset when validating the distribution account balance.
- Update `crypto` for security reasons.
- We are considering all payments no matter the asset when checking for insufficient balance.
- Closes https://github.com/stellar/stellar-disbursement-platform-backend/security/dependabot/3
N/A
[`demo`]: …
> Hot-fix: only consider payments of same asset

- CHANGELOG.md
- helmchart/sdp/Chart.yaml
- main.go
Bump app version and update changelog
--
[TODO or N/A]
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/externalsecrets-common-previews.yaml#L241-L3 …
> chore: bump app version and update changelog

- db/db.go
- internal/serve/httphandler/payments_handler.go
- internal/serve/httphandler/receiver_wallets_handler.go
- internal/serve/httphandler/verifiy_receiver_registration_handler.go
- internal/services/disbursement_management_service.go
- internal/services/disbursement_management_service_test.go
- internal/transactionsubmission/transaction_worker.go
Draft PR to demo the idea of a Post Commit hook for producing events. 
This method allows us to produce the events after the transaction is committed. 
[TODO or N/A]
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/demo/demo-bac …
> [SDP-1114] Fix Race condition when producing events pre-commit. 

- CHANGELOG.md
- helmchart/sdp/Chart.yaml
- main.go
Bump app version and update changelog for hotfix 1.1.5
----
[TODO or N/A]
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/externalsecrets-common-pr …
> chore bump app version and update changelog for hotfix 1.1.5

- dev/Dockerfile-demo-wallet
- dev/README.md
- dev/docker-compose-sdp-anchor.yml
- dev/docker-compose.yml
- dev/env-config-demo-wallet.js
- dev/main.sh
* Added a new Dockerfile for running the demo-wallet client locally. 
* Fix Quickstart links 
* Fix `main.sh` script to only provision missing tenants 
https://stellarorg.atlassian.net/browse/SDP-1105
[TODO or N/A] …
> [SDP-1105] add demo-wallet to docker-compose 

- .github/workflows/docker_image_public_release.yml
- .github/workflows/e2e_integration_test.yml
- README.md
* Cleanup MTN from CI
* Fix ReadME
> SDP-1044 - Cleanup Stellar Multi-tenant

- CHANGELOG.md
- helmchart/sdp/Chart.yaml
- main.go
Release 2.0.0-rc1
https://github.com/stellar/stellar-disbursement-platform-backend/issues/245
[TODO or N/A]
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common- …
> Release 2.0.0-rc1

- db/migrations/sdp-migrations/2024-04-02.0-alter-organizations-table-add-privacy_policy_link.sql
- internal/data/organizations.go
- internal/data/organizations_test.go
- internal/serve/httphandler/profile_handler.go
- internal/serve/httphandler/profile_handler_test.go
Add a column in the organization database called privacy_policy_link, and support it in the organization’s payloads (GET, PATCH)
Each tenant org will have a different privacy policy.
N/A …
> [SDP-702]: Add the privacy_policy_link to the organization database and serve it in a model

- helmchart/sdp/templates/02.3-deployment-tss.yaml
TSS had the wrong `labels` and `selectorLabels`. 
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/externalsecrets-common-previews.yaml#L241-L346 …
> [SDP-1060] MTN helm chart deploy - fix TSS labels

- dev/main.sh
- internal/serve/httphandler/verifiy_receiver_registration_handler.go
Fix main.sh
The check for existing tenants breaks when there are no existing tenants.
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/externalsecre …
> Chore: fix main.sh

- helmchart/sdp/README.md
- helmchart/sdp/minimal-values.yaml
- helmchart/sdp/values.yaml
Cleaning up some dummy data from `values` and `minimal-values`. 
Make sure users of the helm chart are aware that these values are required
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a …
> [SDP-1060] Cleanup `values` and `miniml-values` for helm-chart

- dev/docker-compose-sdp-anchor.yml
- internal/data/payments_state_machine.go
- internal/serve/serve.go
- internal/transactionsubmission/manager.go
- internal/transactionsubmission/manager_test.go
- [Chores] Polishes triggered while doing [SDP-1151](https://stellarorg.atlassian.net/browse/SDP-1151).
- Relates to https://github.com/stellar/stellar-docs/pull/496 …
> [Chores] Polishes triggered while doing SDP-1151

- CHANGELOG.md
- helmchart/sdp/Chart.yaml
- main.go
bump version and update changelog for 1.1.7
releasing 1.1.7 for https://stellarorg.atlassian.net/browse/SDP-1161
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/co …
> bump version and update changelog for 1.1.7

- dev/README.md
- dev/env-config-demo-wallet.js
- dev/main.sh
* change demo-wallet URL to https
* readme fixes
[TODO or N/A]
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/externalsecrets-common-previews.yaml …
> Fix demo-wallet URL and other small cleanups

- stellar-multitenant/internal/httphandler/tenants_handler.go
- stellar-multitenant/internal/provisioning/manager.go
- stellar-multitenant/internal/provisioning/manager_test.go
* When env `BASE_URL` is `localhost` (or an invalid value) and an override isn't passed, tenants get partially created. 
* In order to avoid that, we're validating baseURL earlier 
https://stellarorg.atlassian.net/browse/SDP-1228
[TODO or N/A]
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursement-platform/demo/demo-backend-helm-val …
> [SDP-1228] Partial Tenant Provisioning when base URL is not valid

- README.md
* Remove 2.0.0 RC warning 
* Add link to migration guide
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/externalsecrets-common-previews.yaml#L241- …
> Remove RC warning and add link to migration guide

- internal/circle/client.go
- internal/circle/client_test.go
- internal/circle/environments.go
- internal/circle/errors.go
- internal/circle/transfer.go
- internal/circle/transfer_test.go
- internal/serve/httpclient/mocks/http_client_mock.go
* Setting up the Circle SDK 
* Adding `GET /ping` call https://developers.circle.com/circle-mint/reference/ping
* Adding `POST /transfers` call https://developers.circle.com/circle-mint/reference/createbusinesstransfer
* Adding `GET /transfers/:id` call https://developers.circle.com/circle-mint/reference/getbusinesstransfer
https://stellarorg.atlassian.net/browse/SDP-1189
[`demo`]: …
> [SDP-1189] Setup Circle SDK

- internal/data/circle_transfer_requests.go
- internal/data/circle_transfer_requests_test.go
- internal/data/payments.go
- internal/serve/httphandler/payments_handler.go
- internal/serve/httphandler/payments_handler_test.go
- internal/serve/serve.go
- internal/services/circle_reconciliation_service.go
* Add `circle_transfer_id` to `GET /payments` 
* Add `circle_transfer_id` to `GET /payments/:id` 
Display circle transfer ID in the Payment details page. 
[TODO or N/A] …
> [SDP-1253] Add Circle transfer ID to GET /payments endpoints

- db/migrations/admin-migrations/2024-07-15.0-migrate-data-v1-to-v2-function.sql
Function to migrate single tenant to multi-tenant instance. 
Can run the migration with the following statement : 
```sql
SELECT admin.import_tenant_data_from_v1_to_v2('unhcr');
```
Facilitating data migration for users. 
[TODO or N/A] …
> [SDP-1258] Add function to migrate data from single tenant to multi-tenant instance

- go.list
- go.mod
- go.sum
Bump version of `github.com/gofiber/fiber/v2` and `github.com/getsentry/sentry-go`
Chores
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/externals …
> [SDP-1271] bump lib version

- internal/scheduler/scheduler.go
* Track enqueued jobs to prevent queue congestion 
* Job is not enqueued again if there is another job of the same type in the queue already
[Comment from Marcelo related to queue congestion](https://github.com/stellar/stellar-disbursement-platform-backend/pull/362#issuecomment-2248597894)
* Job execution should ideally be short and we should enforce that through an execution timeout. 
[`demo`]: …
> [SDP-1276] Track enqueued jobs to prevent congestion

- db/migrations/admin-migrations/2024-07-15.0-migrate-data-v1-to-v2-function.sql
- internal/data/payments.go
- internal/services/disbursement_management_service.go
- stellar-auth/pkg/auth/authenticator.go
- stellar-auth/pkg/auth/authenticator_test.go
While working on the data migration from the Python version of this project, we went through a few hiccups. This PR addresses them.
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube00 …
> [SDP-1278] fixes post python migration

- internal/services/wallets/wallets_pubnet.go
Remove Freedom Wallet from the list of pubnet wallets.
Its link is returning 403.
We can add it back once we confirm it's working with the SDP.
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841 …
> Chore: remove Freedom Wallet from the list of pubnet wallets

- .github/workflows/anchor_platform_integration_check.yml
- .github/workflows/ci.yml
- .github/workflows/docker_image_public_release.yml
- .github/workflows/e2e_integration_test.yml
- .github/workflows/singletenant_to_multitenant_db_migration_test.yml
[TODO: Short statement about what is changing.]
[TODO or N/A]
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a93 …
> [DNM] testing github actions

- dev/env-config.js
- helmchart/sdp/Chart.yaml
- helmchart/sdp/README.md
- helmchart/sdp/templates/01.1-configmap-sdp.yaml
- helmchart/sdp/templates/01.4-configmap-dashboard.yaml
- helmchart/sdp/values.yaml
Introduce global value `singleTenantMode` that we can use to configure both the SDP server and dashboard service for single tenant use.
[TODO or N/A] …
> [Chore] Add global singleTenantMode global value for SDP and dashboard

- .github/workflows/anchor_platform_integration_check.yml
- .github/workflows/ci.yml
- .github/workflows/docker_image_public_release.yml
- .github/workflows/e2e_integration_test.yml
- .github/workflows/singletenant_to_multitenant_db_migration_test.yml
[TODO: Short statement about what is changing.]
[TODO or N/A]
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a93 …
> [Testing] remove branch filters and develop branch trigger on push

- internal/serve/httphandler/assets_handler_test.go
Test `Test_AssetHandler_submitChangeTrustTransaction_makeSurePreconditionsAreSetAsExpected` is flaky. 
Instead of comparing absolute times, which can lead to race conditions, we should compare the time difference between when the transaction was created and when it was submitted.
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursemen …
> [SDP-1321] Fix test AssetHandle makeSurePreconditionsAreSetAsExpected

- internal/htmltemplate/tmpl/receiver_register.tmpl
- internal/serve/httphandler/receiver_send_otp_handler.go
- internal/serve/publicfiles/js/receiver_registration.js
Add initial screen so receivers can select between email and phone number.
As part of it, I refactored the code to streamline it and rely on reusable methods rather than manipulating the HTML elements directly all the time.
Address https://stellarorg.atlassian.net/browse/SDP-1295
[`demo`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/stellar-disbursemen …
> [SDP-1295] Add initial screen so receivers can select between email and phoneNumber

- db/migrations/sdp-migrations/2024-09-16.0-receiver-wallet-add-otp-confirmed-by-column.sql
- db/migrations/sdp-migrations/2024-09-16.0-receiver-wallet-add-otp-confirmed-with-column.sql
- internal/data/payments_test.go
- internal/data/receivers_wallet.go
- internal/data/receivers_wallet_test.go
- internal/htmltemplate/tmpl/receiver_registered_successfully.tmpl
- internal/serve/httphandler/payments_handler_test.go
- internal/serve/httphandler/receiver_registration.go
- internal/serve/httphandler/verify_receiver_registration_handler.go
- internal/serve/httphandler/verify_receiver_registration_handler_test.go
* Add contact info to `receiver_registered_successfully.tmpl` 
* Fix unit tests that started breaking because there was no order by applied for get payments. 
https://stellarorg.atlassian.net/browse/SDP-1306 …
> [SDP-1306] Update the `receiver_registered_successfully.tmpl` HTML template to display the contact info

- dev/README.md
* Add the tools needed to run the pre-requisites. Docker, Golang and JQ. 
Reduce friction during setup. 
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-pre …
> Chore: add list of pre-requisites needed to run the SDP setup scripts

- internal/data/fixtures.go
- internal/data/receivers.go
- internal/data/receivers_test.go
- internal/serve/httphandler/delete_contact_info_handler.go
- internal/serve/httphandler/delete_contact_info_handler_test.go
- internal/serve/httphandler/delete_phone_number_handler.go
- internal/serve/serve.go
Update `DELETE .../phone-number/...` to `DELETE .../contact-info/...`
Address https://stellarorg.atlassian.net/browse/SDP-1335
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev …
> [SDP-1335] Update `DELETE .../phone-number/...` to `DELETE .../contact-info/...`

- go.list
- go.mod
- go.sum
- internal/serve/httphandler/disbursement_handler.go
- internal/serve/httphandler/disbursement_handler_test.go
- internal/utils/validation.go
- internal/utils/validation_test.go
Ensure the instruction file has the `.csv` extension.
Also, refactored some unit tests to make them less repetitive.
Address https://stellarorg.atlassian.net/browse/SDP-1245. …
> [SDP-1345] ensure instruction file has the .csv extension

- internal/data/wallets.go
- internal/serve/httphandler/profile_handler.go
- internal/serve/httphandler/profile_handler_test.go
- internal/serve/httphandler/wallets_handler.go
- internal/serve/httphandler/wallets_handler_test.go
- internal/serve/serve.go
- internal/serve/validators/wallet_validator.go
- internal/serve/validators/wallet_validator_test.go
- internal/utils/network_type.go
- internal/utils/network_type_test.go
- internal/utils/utils.go
- internal/utils/validation.go
- internal/utils/validation_test.go
Ensure validation of URLs with the https schema on pubnet, and http/https on testnet.
Address https://stellarorg.atlassian.net/browse/SDP-1261.
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841 …
> [SDP-1361] ensure validation of URLs with the https schema on pubnet

- internal/data/fixtures.go
- internal/data/receivers_test.go
- internal/services/disbursement_management_service_test.go
Remove mentions to country in code. 
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/externalsecrets-common-previews.yaml#L241-L346
[`dev …
> chore - remove mentions to country in code 

- internal/serve/publicfiles/js/receiver_registration.js
Add a method to ensure ReCaptcha is loaded before rendering it. 
https://developers.google.com/recaptcha/docs/loading#loading_recaptcha_asynchronously
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f …
> [SDP-1424] ReCaptcha race condition prevents it from loading

- .github/workflows/anchor_platform_integration_check.yml
- .github/workflows/e2e_integration_test.yml
- .github/workflows/singletenant_to_multitenant_db_migration_test.yml
- Dockerfile
- Dockerfile.development
Revert PR #450: "[SDP-1379] Properly inject the commit hash when running `make docker-build`"
Also, included the `-ldflags "-X main.GitCommit=$GIT_COMMIT"` argument on the delve build, which will probably solve the issue.
Some users reported the issue below with the code added to the Dockerfile:
```
=> => extracting sha256:9cbd322119a1fd6eb9df75f74273f9136ccdf6317336352e605b41d5e5cf941f                                                                                    0.3s
=> CACHED [demo-wallet stage-1 1/3] FROM docker.io/library/nginx:1.17@sha256:6fff55753e3b34e36e24e37039ee9eae1fe38a6420d8ae16ef37c92d1eb26699                               0.0s
=> => resolve docker.io/library/nginx:1.17@sha256:6fff55753e3b34e36e24e37039ee9eae1fe38a6420d8ae16ef37c92d1eb26699 …
```
> Revert PR #450: "[SDP-1379] Properly inject the commit hash when running `make docker-build`"

- dev/main.sh
* Script was deleting all containers. 
* Change `main.sh` script to only kill sdp-mtn containers. 
People love their containers and don't want them dead. 
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a …
> [SDP-1437] main.sh script kills all containers including non-sdp containers

- db/migrations/sdp-migrations/2025-01-24.1-add-create-audit-table-function.sql
- db/migrations/sdp-migrations/2025-01-24.2-add-audit-to-receiver-verifications.sql
- internal/serve/serve.go
- stellar-multitenant/internal/httphandler/tenants_handler_test.go
- stellar-multitenant/internal/provisioning/manager_test.go
- Add a function `create_audit_table` that creates audit table + trigger for a given table dynamically. 
- Use `create_audit_table` for `receiver_verifications` 
- Track changes to `receiver_verifications` table. \ …
> [SDP-1304] Add Audit table to Receiver Verifications

- go.list
- go.mod
- go.sum
- internal/serve/httphandler/disbursement_handler.go
- internal/serve/httphandler/disbursement_handler_test.go
Strip out BOM when validating CSV headers. 
BOM (Byte Order Mark) isn't handled properly by golang's csv reader 
https://github.com/golang/go/issues/33887
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a …
> [SDP-1538] Skip BOM when parsing CSV file

- internal/data/query_params.go
- internal/data/receivers.go
- internal/data/receivers_test.go
- internal/serve/httphandler/export_handler.go
- internal/serve/httphandler/export_handler_test.go
- Add `Receiver.PhoneNumber` and `Receiver.Email` to Payment export
Facilitate reconciliation. 
[`pr-preview secrets`]: https://github.com/stellar/kube/blob/d3e4f5dd8aa4c13b45a31a5a937f3e98841171a7/kube001-dev/namespaces/common-previews/ext …
> [SDP-1541] Surface Receiver Contact Info during Payment Export

- CHANGELOG.md
- internal/htmltemplate/htmltemplate.go
- internal/htmltemplate/htmltemplate_test.go
- internal/htmltemplate/tmpl/email/staff_forgot_password_message.tmpl
- internal/serve/httphandler/forgot_password_handler.go
- internal/serve/httphandler/forgot_password_handler_test.go
Improve UX on the fogotPassword->resetPassword flow by embedding the reset token in the URL, so it can be parsed by the FE.
Address https://stellarorg.atlassian.net/browse/SDP-1496. …
> [SDP-1496] Improve UX on the fogotPassword->resetPassword flow

- .github/pull_request_template.md
- CHANGELOG.md
Refactor the PR checklist.
It was too long and redundant. By reducing it we make it easier to follow.
> Chore: refactor the PR checklist

- CHANGELOG.md
- db/migrations/sdp-migrations/2025-03-11.0-update-receiver-wallets-memo-column-to-text.sql
- internal/data/disbursement_instructions.go
- internal/data/disbursement_instructions_test.go
- internal/serve/httphandler/disbursement_handler.go
- internal/serve/httphandler/disbursement_handler_test.go
- internal/serve/validators/disbursement_instructions_validator.go
- internal/serve/validators/disbursement_instructions_validator_test.go
- internal/services/paymentdispatchers/memo_resolver.go
- internal/services/paymentdispatchers/memo_resolver_test.go
- pkg/schema/memo.go
- pkg/schema/memo_test.go
Support memos when ingesting the CSV instructions.
Address https://stellarorg.atlassian.net/browse/SDP-1480.
> [SDP-1480] Support memos when ingesting the CSV instructions

- .github/workflows/ci.yml
- .golangci.yml
- CHANGELOG.md
Bump checks versions so they work with the latest Golang versions.
> Chore: bump checks versions so they work with the latest Golang versions

- .github/workflows/e2e_integration_test.yml
- CHANGELOG.md
- internal/integrationtests/scripts/e2e_integration_test.sh
- internal/integrationtests/server_api.go
Add Circle Payouts API to the e2e integration tests
For better test coverage.
> [SDP-1574] Add Circle Payouts API to the e2e integration tests

- internal/serve/httperror/code.go
- internal/serve/httperror/httperror.go
- internal/serve/httphandler/receiver_registration_handler.go
- internal/serve/httphandler/receiver_registration_handler_test.go
- internal/serve/httphandler/receiver_send_otp_handler.go
- internal/serve/httphandler/receiver_send_otp_handler_test.go
- internal/serve/httphandler/verify_receiver_registration_handler.go
- internal/serve/httphandler/verify_receiver_registration_handler_test.go
- internal/serve/middleware/middleware.go
- internal/serve/middleware/middleware_test.go
Return error codes for errors in the SEP-24 flow
To allow localization of these errors.
> SDL-1578: Return error codes for errors in the SEP-24 flow

- dev/README.md
- dev/main.sh
Fixes #623
Fix printed owner email in `main.sh` script and README documentation. 
https://github.com/stellar/stellar-disbursement-platform-backend/issues/623
[TODO or N/A]
> SDP-1613: main.sh echo email does not match created email

- internal/integrationtests/server_api.go
Fix e2e tests 
SEP-24 registration URLs changed.
> SDP-1659: Fix e2e tests after SEP-24 app changes

- README.md
- helmchart/sdp/README.md
- helmchart/sdp/minimal-values.yaml
* change `minimal-values.yaml` to use edge image. 
* documentation polishes.
> SDP-1658: Helm Chart documentation polish

- CHANGELOG.md
> Mark 3.7.0 as released

- CHANGELOG.md
- README.md
- internal/transactionsubmission/engine/signing/signer_router_test.go
Add Several badges to the README.md:
This includes the DeepWiki badge, which ensures DeepWiki will re-index this repo once a week.
📈  Kaizen
> Add badges to the README.md file

- internal/serve/serve.go
adjust the paths from api-keys/api-keys/{id} -> api-keys/{id}
[TODO or N/A]
> feat/adjust GetByID and Delete api key paths

- .github/workflows/ci.yml
This pins the version of `@bitnami/readme-generator-for-helm` to 2.7.0.
2.7.1 was released hours ago and introduced what appears to be a bug that is causing CI to break in PRs. Let's pin the version and explicitly upgrade.
```diff
diff --git a/helmchart/sdp/README.md b/helmchart/sdp/README.md
index b021edd..5610d0d 100644
--- a/helmchart/sdp/README.md
+++ b/helmchart/sdp/README.md
@@ -139,7 +139,7 @@ With the tunnel running, you can access the services using the following URLs:
-These parameters are shared by all charts.
+ These parameters are shared by all charts.
| Name                                                   | Description                                                                                                                         | Value …
```
> Pin @bitnami/readme-generator-for-helm version

- dev/scripts/add_test_users.sh
Fixes the script by replacing `bash` with `sh` and `curl` with `wget`.
`./main.sh` doesn't complete.
N/A
> Fix: Update add_tests_users.sh in main.sh for Alpine Linux

- .env.example
- dev/docker-compose-sdp-anchor.yml
- dev/docker-compose-tss.yml
This updates the `.env.example` and the Docker Compose files with the new embedded wallet configurations.
They were missing.
N/A
> Update docker compose for embedded wallets

- .github/workflows/ci.yml
- CHANGELOG.md
- internal/serve/httphandler/export_handler.go
- internal/serve/httphandler/export_handler_test.go
- Add Receiver External  ID to Export Payments endpoint
https://stellarorg.atlassian.net/browse/SDP-1731
> SDP-1731: Add receiver external ID to export payments

- internal/services/embedded_wallet_service.go
- internal/services/embedded_wallet_service_test.go
This fixes the rollback when either of the transactions updates fail due to an error. This also adds a check for duplicate credential IDs before creating any transactions.
Previously, if the embedded wallet update fails due to a duplicate credential ID, the TSS transaction is not rolled back.
N/A
> Fix: Check credential ID before creating TSS transaction

- internal/data/embedded_wallet.go
- internal/data/embedded_wallet_test.go
- internal/serve/httphandler/wallet_creation_handler.go
- internal/serve/httphandler/wallet_creation_handler_test.go
Updates the credential ID validation in the embedded wallet model.
Missed after updating the previous PR to increase the column length https://github.com/stellar/stellar-disbursement-platform-backend/pull/800
N/A
> Fix: Update missed 64 char credential ID check

- internal/data/embedded_wallet.go
- internal/data/embedded_wallet_test.go
- internal/serve/httphandler/wallet_creation_handler.go
- internal/serve/httphandler/wallet_creation_handler_test.go
- internal/services/wallet_creation_from_submitter_service.go
- internal/services/wallet_creation_from_submitter_service_test.go
Merge `feature/c-accounts` into `feature/smart-wallet-demo`
Keep feature branch in sync
N/A
> Chore: Merge `feature/c-accounts` into `feature/smart-wallet-demo`

- internal/scheduler/jobs/job.go
Allow scheduler to run every 1s.
To improve the response time for the smart wallet demo.
> jobs: allow scheduler jobs to run every 1s

- internal/serve/httphandler/receiver_handler_test.go
- internal/serve/httphandler/update_receiver_handler.go
> SDP-1818 change duplicate receiver wallet status code

- README.md
- dev/README.md
- helmchart/sdp/README.md
[TODO: Brief description of the changes]
[TODO or N/A]
> SDP-1776 SEP10/SEP24 documentation

- internal/data/embedded_wallet.go
- internal/services/embedded_wallet_service.go
- internal/services/embedded_wallet_service_test.go
This normalizes the storage of the emails before storing querying the embedded wallets table.
The `/resend-invite` API is case-sensitive.
N/A
> Fix: Normalize email casing before storing and query embedded wallets

- .github/workflows/contract_build.yml
This updates the contracts build workflow.
It's really barebones in its current state.
N/A
> CI: Update contracts build workflow
